/*******************************************************************
 * Decompiled By: AgreedBog381
 * Decompiled File: seoul_anim.gsc
 * Game: Call of Duty: Advanced Warfare
 * Platform: PC
 * Function Count: 5
 * Decompile Time: 247 ms
 * Timestamp: 4/20/2022 8:21:02 PM
*******************************************************************/

//Function Number: 1
func_0C7A()
{
	thread func_6A58();
	thread func_9C83();
	thread func_5D34();
	level.var_78A9["atlas_guy1"]["seo_meet_atlas"] = %seo_meet_atlas_atlas01;
	level.var_78A9["atlas_guy2"]["seo_meet_atlas"] = %seo_meet_atlas_atlas02;
	level.var_78A9["cormack"]["seo_meet_atlas"] = %seo_meet_atlas_cormack;
	level.var_78A9["gideon"]["seo_meet_atlas"] = %seo_meet_atlas_gideon;
	level.var_78A9["jackson"]["seo_meet_atlas"] = %seo_meet_atlas_guy01;
	level.var_78A9["vip"]["seo_meet_atlas"] = %seo_meet_atlas_vip01;
	if(level.currentgen)
	{
		level.var_78A9["vip"]["seo_post_meet_atlas_walk"] = %civilian_run_hunched_a;
	}

	level.var_78A9["will_irons"]["seo_meet_atlas"] = %seo_meet_atlas_will;
	level.var_78A9["cormack"]["seo_canal_debrief_intro_cormack"] = %seo_canal_debrief_intro_cormack;
	level.var_78A9["cormack"]["seo_canal_debrief_kneeling_idle_cormack"][0] = %seo_canal_debrief_kneeling_idle_cormack;
	level.var_78A9["cormack"]["seo_canal_debrief_trans2_prone_cormack"] = %seo_canal_debrief_trans2_prone_cormack;
	level.var_78A9["cormack"]["seo_canal_debrief_prone_idle_cormack"][0] = %seo_canal_debrief_prone_idle_cormack;
	level.var_78A9["cormack"]["seo_canal_overlook_anim"][0] = %casual_crouch_idle;
	level.var_78A9["will_irons"]["seo_canal_overlook_anim"][0] = %casual_crouch_idle;
	level.var_78A9["jackson"]["seo_canal_overlook_anim"][0] = %casual_crouch_idle;
	level.var_78A9["will_irons"]["finale_pt01"] = %seo_finale_runup_will;
	level.var_78A9["will_irons"]["finale_idle_will"][0] = %seo_finale_idle_will;
	level.var_78A9["will_irons"]["finale_plantbomb"] = %seo_finale_plantbomb_will;
	level.var_78A9["will_irons"]["finale_pt02"] = %seo_finale_part2_will;
	level.var_78A9["cormack"]["finale_pt03"] = %seo_finale_phase2_silo_collapse_cormack;
	level.var_78A9["cormack"]["boost_jump_128_across_256_down"] = %boost_jump_128_across_256_down;
	level.var_78A9["cormack"]["boost_jump_256_across_256_down"] = %boost_jump_256_across_256_down;
	level.var_78A9["cormack"]["boost_jump_128_across_196_down"] = %boost_jump_128_across_196_down;
	level.var_78A9["cormack"]["boost_jump_128_across_128_down"] = %boost_jump_128_across_128_down;
	level.var_78A9["cormack"]["boost_jump_512_across_128_down"] = %boost_jump_512_across_128_down;
	level.var_78A9["cormack"]["traverse_drop_512"] = %traverse_drop_512;
	level.var_78A9["cormack"]["cornerstndr_alert_2_lean"] = %cornerstndr_alert_2_lean;
	level.var_78A9["cormack"]["cornercrl_alert_idle_single"] = %cornercrl_alert_idle;
	level.var_78A9["cormack"]["corner_standl_alert_twitch04"] = %corner_standl_alert_twitch04;
	level.var_78A9["will_irons"]["boost_jump_256_across_256_down"] = %boost_jump_256_across_256_down;
	level.var_78A9["will_irons"]["boost_jump_128_across_256_down"] = %boost_jump_128_across_256_down;
	level.var_78A9["will_irons"]["boost_jump_128_across_196_down"] = %boost_jump_128_across_196_down;
	level.var_78A9["will_irons"]["boost_jump_128_across_128_down"] = %boost_jump_128_across_128_down;
	level.var_78A9["will_irons"]["boost_jump_512_across_128_down"] = %boost_jump_512_across_128_down;
	level.var_78A9["will_irons"]["boost_jump_512_across_128_over"] = %boost_jump_512_across_128_down;
	level.var_78A9["will_irons"]["traverse_drop_512"] = %traverse_drop_512;
	level.var_78A9["will_irons"]["cornerstndr_alert_2_lean"] = %cornerstndr_alert_2_lean;
	level.var_78A9["will_irons"]["cornercrl_alert_idle_single"] = %cornercrl_alert_idle;
	level.var_78A9["will_irons"]["corner_standl_alert_twitch04"] = %corner_standl_alert_twitch04;
	level.var_78A9["will_irons"]["mulekick_transition"] = %ny_harbor_breech_mulekick_guy1_transition;
	level.var_78A9["will_irons"]["idle_at_door"][0] = %ny_harbor_breech_mulekick_guy1_idle;
	level.var_78A9["will_irons"]["mulekick_kick"] = %ny_harbor_breech_mulekick_guy1_kick;
	level.var_78A9["will_irons"]["doorkick_2_cqbrun"] = %doorkick_2_cqbrun;
	level.var_78A9["will_irons"]["doorkick_2_cqbwalk"] = %doorkick_2_cqbwalk;
	level.var_78A9["will_irons"]["foyer_door_kick_a"] = %ch_castle_guard_doorkick_a;
	level.var_78A9["will_irons"]["foyer_door_kick_b"] = %ch_castle_guard_doorkick_b;
	level.var_78A9["cormack"]["walker_step_over"] = %seo_walker_intro_guy;
	level.var_78A9["will_irons"]["walker_step_over"] = %seo_walker_intro_guy1;
	level.var_78A9["generic"]["ny_harbor_hind_sitting_idle_01"][0] = %ny_harbor_hind_sitting_idle_01;
	level.var_78A9["generic"]["ny_harbor_hind_sitting_idle_02"][0] = %ny_harbor_hind_sitting_idle_02;
	level.var_78A9["generic"]["ny_harbor_hind_sitting_idle_03"][0] = %ny_harbor_hind_sitting_idle_03;
	level.var_78A9["generic"]["ny_harbor_hind_sitting_idle_04"][0] = %ny_harbor_hind_sitting_idle_04;
	level.var_78A9["generic"]["civilian_sitting_business_lunch_a_1"][0] = %civilian_sitting_business_lunch_a_1;
	level.var_78A9["generic"]["civilian_sitting_business_lunch_b_1"][0] = %civilian_sitting_business_lunch_b_1;
	level.var_78A9["generic"]["guarda_sit_sleeper_idle"][0] = %guarda_sit_sleeper_idle;
	level.var_78A9["generic"]["det_school_enter_pt2_npc_deadbody_01"][0] = %det_school_enter_pt2_npc_deadbody_01;
	level.var_78A9["generic"]["det_school_enter_pt2_npc_deadbody_02"][0] = %det_school_enter_pt2_npc_deadbody_02;
	level.var_78A9["generic"]["det_school_enter_pt2_npc_deadbody_03"][0] = %det_school_enter_pt2_npc_deadbody_03;
	level.var_78A9["generic"]["det_school_enter_pt2_npc_deadbody_04"][0] = %det_school_enter_pt2_npc_deadbody_04;
	level.var_78A9["generic"]["det_school_enter_pt2_npc_deadbody_05"][0] = %det_school_enter_pt2_npc_deadbody_05;
	level.var_78A9["generic"]["det_school_enter_pt2_npc_deadbody_06"][0] = %det_school_enter_pt2_npc_deadbody_06;
	level.var_78A9["generic"]["det_school_enter_pt2_npc_deadbody_07"][0] = %det_school_enter_pt2_npc_deadbody_07;
	level.var_78A9["generic"]["det_school_enter_pt2_npc_deadbody_08"][0] = %det_school_enter_pt2_npc_deadbody_08;
	level.var_78A9["generic"]["africa_execution_prisoner_1"] = %africa_execution_prisoner_1;
	level.var_78A9["generic"]["africa_execution_prisoner_2"] = %africa_execution_prisoner_2;
	level.var_78A9["generic"]["africa_execution_prisoner_3"] = %africa_execution_prisoner_3;
	level.var_78A9["generic"]["africa_execution_soldier_1"] = %africa_execution_soldier_1;
	level.var_78A9["generic"]["africa_execution_soldier_2"] = %africa_execution_soldier_2;
	level.var_78A9["generic"]["ny_harbor_hind_sitting_idle_01_single"] = %ny_harbor_hind_sitting_idle_01;
	level.var_78A9["generic"]["ny_harbor_hind_sitting_idle_02_single"] = %ny_harbor_hind_sitting_idle_02;
	level.var_78A9["generic"]["ny_harbor_hind_sitting_idle_03_single"] = %ny_harbor_hind_sitting_idle_03;
	level.var_78A9["generic"]["ny_harbor_hind_sitting_idle_04_single"] = %ny_harbor_hind_sitting_idle_04;
	level.var_78A9["generic"]["civilian_sitting_business_lunch_a_1_single"] = %civilian_sitting_business_lunch_a_1;
	level.var_78A9["generic"]["civilian_sitting_business_lunch_b_1_single"] = %civilian_sitting_business_lunch_b_1;
	level.var_78A9["generic"]["guarda_sit_sleeper_idle_single"] = %guarda_sit_sleeper_idle;
	level.var_78A9["generic"]["ny_manhattan_sandman_signal_hold"] = %ny_manhattan_sandman_signal_hold;
	level.var_78A9["generic"]["ny_manhattan_sandman_signal_towalk"] = %ny_manhattan_sandman_signal_towalk;
	level.var_78A9["generic"]["explosivebreach_v1_stackl_idle"][0] = %explosivebreach_v1_stackl_idle;
	level.var_78A9["generic"]["breach_sh_stackr1_idle"][0] = %breach_sh_stackr1_idle;
	level.var_78A9["generic"]["patrol_bored_patrolwalk_single"] = %patrol_bored_patrolwalk;
	level.var_78A9["generic"]["bet_casual_startstop_idle_gideon"][0] = %bet_casual_startstop_idle_gideon;
	level.var_78A9["generic"]["launchfacility_b_blast_door_seq_waveidle"][0] = %launchfacility_b_blast_door_seq_waveidle;
	level.var_78A9["generic"]["ny_manhattan_radio_sandman_talk"][0] = %ny_manhattan_radio_sandman_talk;
	level.var_78A9["generic"]["corner_nowall_l_stand_idle_twitch"][0] = %coverstand_look_idle;
	level.var_78A9["generic"]["corner_left_crouch_alerttwitch1"][0] = %covercrouch_hide_idle;
	level.var_78A9["generic"]["casual_crouch_idle"][0] = %casual_crouch_idle;
	level.var_78A9["generic"]["corner_right_crouch_alerttwitch1"][0] = %covercrouch_hide_idle;
	level.var_78A9["generic"]["casual_crouch_v2_talk"][0] = %casual_crouch_v2_talk;
	level.var_78A9["generic"]["london_sandman_sas_talk_friendly"] = %london_sandman_sas_talk_friendly;
	level.var_78A9["cormack"]["london_sandman_sas_talk_sandman"] = %london_sandman_sas_talk_sandman;
	level.var_78A9["cormack"]["patrolstand_look"][0] = %patrolstand_look;
	level.var_78A9["generic"]["cliffhanger_jump_price_reach"] = %cliffhanger_jump_price_reach;
	level.var_78A9["generic"]["prague_scaffold_climb_getoff"] = %prague_scaffold_climb_getoff;
	level.var_78A9["generic"]["africa_stack_on_wall_idle"][0] = %africa_stack_on_wall_idle;
	level.var_78A9["generic"]["crouch_alert_b_idle1"][0] = %casual_crouch_twitch;
	level.var_78A9["generic"]["shotgunbreach_v1_stacka_idle"][0] = %shotgunbreach_v1_stacka_idle;
	level.var_78A9["generic"]["prague_interrogate_1short_civ_idle"][0] = %prague_interrogate_1short_civ_idle;
	level.var_78A9["generic"]["prague_riotshield_idle_civ01_v1"][0] = %prague_riotshield_idle_civ01_v1;
	level.var_78A9["generic"]["prague_riotshield_idle_civ01_v2"][0] = %prague_riotshield_idle_civ01_v2;
	level.var_78A9["generic"]["prague_interrogate_3_civ_idle"][0] = %prague_interrogate_3_civ_idle;
	level.var_78A9["generic"]["civilian_sitting_talking_b_2"][0] = %civilian_sitting_talking_b_2;
	level.var_78A9["generic"]["ch_pragueb_15_6_wounded_civ_01"][0] = %ch_pragueb_15_6_wounded_civ_01;
	level.var_78A9["generic"]["ch_pragueb_15_6_wounded_civ_02"][0] = %ch_pragueb_15_6_wounded_civ_02;
	level.var_78A9["generic"]["ch_pragueb_15_6_wounded_civ_03"][0] = %ch_pragueb_15_6_wounded_civ_03;
	level.var_78A9["generic"]["ch_pragueb_15_6_wounded_civ_04"][0] = %ch_pragueb_15_6_wounded_civ_04;
	level.var_78A9["generic"]["ch_pragueb_15_6_wounded_civ_05"][0] = %ch_pragueb_15_6_wounded_civ_05;
	level.var_78A9["generic"]["ch_pragueb_15_6_wounded_civ_06"][0] = %ch_pragueb_15_6_wounded_civ_06;
	level.var_78A9["generic"]["civilian_sitting_talking_a_1"][0] = %civilian_sitting_talking_a_1;
	level.var_78A9["generic"]["civilian_texting_sitting"][0] = %civilian_texting_sitting;
	level.var_78A9["generic"]["civilian_texting_standing"][0] = %civilian_texting_standing;
	level.var_78A9["generic"]["africa_civ_washingclothes"][0] = %africa_civ_washingclothes;
	level.var_78A9["generic"]["london_civ_idle_foldarms2"][0] = %london_civ_idle_foldarms2;
	level.var_78A9["generic"]["london_civ_idle_scratchnose"][0] = %london_civ_idle_scratchnose;
	level.var_78A9["generic"]["parabolic_leaning_guy_smoking_idle"][0] = %parabolic_leaning_guy_smoking_idle;
	lib_A506::func_807("generic","puff",::lib_A5CE::func_1D6C,"parabolic_leaning_guy_smoking_idle");
	level.var_78A9["generic"]["civilian_smoking_b"][0] = %civilian_smoking_b;
	lib_A506::func_807("generic","fx_smoke_breath",::lib_A5CE::func_1D6C,"civilian_smoking_b");
	level.var_78A9["generic"]["london_civ_idle_lookbehind"][0] = %london_civ_idle_lookbehind;
	level.var_78A9["generic"]["civilian_reader_1"][0] = %civilian_reader_1;
	level.var_78A9["generic"]["civilian_reader_2"][0] = %civilian_reader_2;
	level.var_78A9["generic"]["seo_run_gunbehind_guy02"] = %seo_run_gunbehind_guy02;
	level.var_78A9["generic"]["seo_run_gununderarm_guy01"] = %seo_run_gununderarm_guy01;
	level.var_78A9["generic"]["seo_run_gununderarm_guy02"] = %seo_run_gununderarm_guy02;
	level.var_78A9["generic"]["seo_run_gunup_guy01"] = %seo_run_gunbehind_guy01;
	level.var_78A9["generic"]["seo_run_gunup_guy02"] = %seo_run_gunup_guy02;
	level.var_78A9["generic"]["ch_castle_8_1_prisoners_sleeping_sitting"][0] = %ch_castle_8_1_prisoners_sleeping_sitting;
	level.var_78A9["generic"]["afgan_caves_sleeping_guard_idle"][0] = %afgan_caves_sleeping_guard_idle;
	level.var_78A9["generic"]["sf_a_civ_injured_seated_crying"][0] = %sf_a_civ_injured_seated_crying;
	level.var_78A9["generic"]["sf_a_civ_injured_seated_face"][0] = %sf_a_civ_injured_seated_face;
	level.var_78A9["generic"]["sf_a_civ_injured_seated_helped"][0] = %sf_a_civ_injured_seated_helped;
	level.var_78A9["generic"]["sf_a_civ_injured_seated_helper"][0] = %sf_a_civ_injured_seated_helper;
	level.var_78A9["generic"]["sf_a_civ_injured_seated_mourner"][0] = %sf_a_civ_injured_seated_mourner;
	level.var_78A9["generic"]["sf_a_civ_injured_seated_mourned"][0] = %sf_a_civ_injured_seated_mourned;
	level.var_78A9["generic"]["sf_a_civ_injured_seated_neck"][0] = %sf_a_civ_injured_seated_neck;
	level.var_78A9["generic"]["civilian_sitting_business_lunch_A_1"][0] = %civilian_sitting_business_lunch_a_1;
	level.var_78A9["generic"]["hijack_tarmac_injured_hands_on_knees"][0] = %hijack_tarmac_injured_hands_on_knees;
	level.var_78A9["generic"]["dead_body_pose5"] = %det_school_enter_pt2_npc_deadbody_01;
	level.var_78A9["generic"]["dead_body_pose1"] = %paris_npc_dead_poses_v17;
	level.var_78A9["generic"]["dead_body_pose2"] = %paris_npc_dead_poses_v08;
	level.var_78A9["generic"]["dead_body_pose3"] = %paris_npc_dead_poses_v20;
	level.var_78A9["generic"]["dead_body_pose4"] = %det_school_enter_pt2_npc_deadbody_12;
	level.var_78A9["generic"]["dead_body_pose6"] = %hijack_hallway_dead_pose_terrorist;
	level.var_78A9["generic"]["warbird_jumper_drop_1"][0] = %guardb_sit_drinker_idle;
	level.var_78A9["generic"]["warbird_jumper_drop_2"][0] = %harbor_floating_idle_01;
	level.var_78A9["generic"]["warbird_jumper_drop_3"][0] = %hunted_tunnel_guy1_idle;
	level.var_78A9["generic"]["warbird_jumper_drop_4"][0] = %intro_helicopter_idle_guy3;
	level.var_78A9["generic"]["ny_harbor_hang_idle_1"] = %ny_harbor_hang_idle_1;
	level.var_78A9["generic"]["ny_harbor_hang_idle_2"] = %ny_harbor_hang_idle_2;
	level.var_78A9["generic"]["warbird_jumper_jump"] = %cliffhanger_truck_price_jumpa;
	level.var_78A9["generic"]["warbird_jumper_land_1"] = %boost_jump_land_2_cqb;
	level.var_78A9["generic"]["warbird_jumper_land_2"] = %hijack_generic_stumble_crouch2;
	level.var_78A9["generic"]["warbird_jumper_land_3"] = %hijack_generic_stumble_stand2;
	level.var_78A9["generic"]["warbird_jumper_land_4"] = %run_pain_stomach_stumble;
	level.var_78A9["generic"]["warbird_jumper_land_5"] = %run_pain_stumble;
	level.var_78A9["generic"]["warbird_jumper_land_6"] = %run_react_stumble;
	level.var_78A9["generic"]["boost_jump_128_across_256_down"] = %boost_jump_128_across_256_down;
	level.var_78A9["generic"]["boost_jump_land_2_stop_b"] = %boost_jump_land_2_stop_b;
	level.var_78A9["generic"]["ny_manhattan_rooftop_extraction_delta_ride_idlec"][0] = %ny_manhattan_rooftop_extraction_delta_ride_idlec;
	level.var_78A9["generic"]["coup_passenger_idle"][0] = %coup_passenger_idle;
	level.var_78A9["generic"]["africa_technical_passenger_rside_idle"][0] = %africa_technical_passenger_rside_idle;
	level.var_78A9["generic"]["ny_manhattan_rooftop_extraction_delta_ride_idlec_single"] = %ny_manhattan_rooftop_extraction_delta_ride_idlec;
	level.var_78A9["generic"]["coup_passenger_idle_single"] = %coup_passenger_idle;
	level.var_78A9["generic"]["africa_technical_passenger_rside_idle_single"] = %africa_technical_passenger_rside_idle;
	level.var_78A9["generic"]["prague_teargas_run_1_twitch"] = %prague_teargas_run_1_twitch;
	level.var_78A9["generic"]["paris_delta_pull_movemanhole__idle_guy2"] = %paris_delta_pull_movemanhole__idle_guy2;
	level.var_78A9["generic"]["berlin_reverse_breach_guy_getup"] = %berlin_reverse_breach_guy_getup;
	level.var_78A9["generic"]["paris_delta_pull_movemanhole_guy2"] = %paris_delta_pull_movemanhole_guy2;
	level.var_78A9["generic"]["prague_teargas_run_1"] = %prague_teargas_run_1;
	level.var_78A9["generic"]["ai_attacked_german_shepherd_02_getup_a"] = %ai_attacked_german_shepherd_02_getup_a;
	level.var_78A9["generic"]["sinkhole_fall"] = %bog_b_rpg_fall_death;
	level.var_78A9["generic"]["fusion_zipline_guy1"] = %fusion_zipline_guy1;
	level.var_78A9["generic"]["fusion_zipline_guy2"] = %fusion_zipline_guy2;
	level.var_78A9["generic"]["bh_fastrope_loop"][0] = %bh_fastrope_loop;
	level.var_78A9["generic"]["boost_jump_land_2_stop_a"] = %boost_jump_land_2_stop_a;
	level.var_78A9["generic"]["boost_jump_land_2_stop_b"] = %boost_jump_land_2_stop_b;
	level.var_78A9["generic"]["boost_jump_land_2_stop_c"] = %boost_jump_land_2_stop_c;
	level.var_78A9["generic"]["boost_jump_land_2_cqb"] = %boost_jump_land_2_cqb;
	level.var_78A9["generic"]["boost_jump_land_2_stop_look_around"] = %boost_jump_land_2_stop_look_around;
	level.var_78A9["generic"]["boost_jump_land_2_stop_slide_a"] = %boost_jump_land_2_stop_slide_a;
	level.var_78A9["generic"]["boost_jump_land_2_stop_slide_b"] = %boost_jump_land_2_stop_slide_b;
	level.var_78A9["generic"]["boost_jump_512_across_128_down"] = %boost_jump_512_across_128_down_slow_test;
	level.var_78A9["generic"]["boost_jump_512_across_270_down"] = %boost_jump_512_across_270_down;
	level.var_78A9["generic"]["boost_jump_256_across_128_down"] = %boost_jump_256_across_128_down_slow_test;
	level.var_78A9["generic"]["hms_greece_traverse_railing_drop_36_128_b"] = %hms_greece_traverse_railing_drop_36_128_b;
	level.var_78A9["generic"]["hms_greece_traverse_railing_drop_36_128"] = %hms_greece_traverse_railing_drop_36_128;
	level.var_78A9["generic"]["g_rocket_jump_160_airbrake_512"] = %g_rocket_jump_160_airbrake_512;
	level.var_78A9["generic"]["boost_jump_512_across"] = %boost_jump_512_across;
	level.var_78A9["generic"]["boost_jump_256_across_128_over"] = %boost_jump_256_across_128_over;
	level.var_78A9["generic"]["boost_jump_128_across_140_up"] = %boost_jump_128_across_140_up;
	level.var_78A9["generic"]["boost_jump_256_across_140_down"] = %boost_jump_256_across_140_down;
	level.var_A3C0 = ["boost_jump_land_2_stop_a","boost_jump_land_2_stop_b","boost_jump_land_2_stop_c","boost_jump_land_2_cqb","boost_jump_land_2_stop_look_around","boost_jump_land_2_stop_slide_a","boost_jump_land_2_stop_slide_b"];
	level.var_157D = ["boost_jump_land_2_stop_look_around","boost_jump_land_2_stop_slide_a","boost_jump_land_2_stop_slide_b"];
	level.var_78A9["generic"]["det_casual_gestures_r_alt_lookaround_joker"] = %det_casual_gestures_r_alt_lookaround_joker;
	level.var_78A9["generic"]["patrolstand_look"] = %patrolstand_look;
	level.var_78A9["generic"]["patrolstand_look_loop"][0] = %patrolstand_look;
	level.var_78A9["generic"]["london_civ_idle_wave"] = %london_civ_idle_wave;
	level.var_78A9["generic"]["det_casual_gestures_r_alt_lookr_joker"] = %det_casual_gestures_r_alt_lookr_joker;
	level.var_78A9["generic"]["det_casual_gestures_r_alt_high_wave_burke"] = %det_casual_gestures_r_alt_high_wave_burke;
	level.var_78A9["generic"]["so_hijack_execution_aim_down_idle_terrorist"][0] = %so_hijack_execution_aim_down_idle_terrorist;
	level.var_78A9["grenade_training"]["berlin_spotter_spot_idle"][0] = %berlin_spotter_spot_idle;
	level.var_78A9["grenade_training"]["det_gate_decon_guard1"][0] = %det_gate_decon_guard1;
	level.var_78A9["grenade_training"]["africa_militia_carry_crate_guy1"] = %africa_militia_carry_crate_guy1;
	level.var_78A9["grenade_training"]["africa_militia_carry_crate_guy2"] = %africa_militia_carry_crate_guy2;
	level.var_78A9["grenade_training"]["det_gate_decon_guard2"] = %det_gate_decon_guard2;
	level.var_78A9["generic"]["cornerstndr_alert_2_lean"] = %cornerstndr_alert_2_lean;
	level.var_78A9["generic"]["cornercrl_alert_idle_single"] = %cornercrl_alert_idle;
	level.var_78A9["generic"]["corner_standl_alert_twitch04"] = %corner_standl_alert_twitch04;
	level.var_78A9["generic"]["boost_jump_128_across_196_down"] = %boost_jump_128_across_196_down;
	level.var_78A9["generic"]["boost_jump_128_across_128_down"] = %boost_jump_128_across_128_down;
	level.var_78A9["generic"]["boost_jump_128_across_256_down"] = %boost_jump_128_across_256_down;
	level.var_78A9["generic"]["boost_jump_256_across_256_down"] = %boost_jump_256_across_256_down;
	level.var_78A9["generic"]["boost_jump_512_across_128_down"] = %boost_jump_512_across_128_down;
	level.var_78A9["generic"]["traverse_drop_512"] = %traverse_drop_512;
	level.var_78A9["generic"]["sanfran_boost_takedown_a_guy2"] = %sanfran_boost_takedown_a_guy2;
	level.var_78A9["generic"]["africa_soap_kickin_door"] = %africa_soap_kickin_door;
	lib_A506::func_80F("generic","door_open","door_smash_open","africa_soap_kickin_door");
	level.var_78A9["generic"]["seo_soldiers_dying_idle_guy02"][0] = %seo_soldiers_dying_idle_guy02;
	level.var_78A9["generic"]["seo_soldiers_dying_idle_guy01"][0] = %seo_soldiers_dying_idle_guy01;
	level.var_78A9["generic"]["seo_turn_gesturetomove_guy01"] = %seo_turn_gesturetomove_guy01;
	level.var_78A9["generic"]["seo_turn_gesturetomove_guy02"] = %seo_turn_gesturetomove_guy02;
	level.var_78A9["generic"]["seo_move_rookierun_01"] = %seo_move_rookierun_01;
	level.var_78A9["generic"]["seo_move_rookierun_02"] = %seo_move_rookierun_02;
	level.var_78A9["generic"]["seo_move_with_launcher_01"] = %seo_move_with_launcher_01;
	level.var_78A9["generic"]["seo_run_with_mobilecover_guy01"] = %seo_run_with_mobilecover_guy01;
	level.var_78A9["generic"]["seo_run_with_mobilecover_guy02"] = %seo_run_with_mobilecover_guy02;
	level.var_78A9["generic"]["seo_injured_soldier_drag_guy01"] = %seo_injured_soldier_drag_guy01;
	level.var_78A9["generic"]["seo_injured_soldier_drag_guy02"] = %seo_injured_soldier_drag_guy02;
	level.var_78A9["generic"]["seo_injured_soldier_idle01_guy01"][0] = %seo_injured_soldier_idle01_guy01;
	level.var_78A9["generic"]["seo_injured_soldier_idle01_guy02"][0] = %seo_injured_soldier_idle01_guy02;
	level.var_78A9["generic"]["seo_injured_soldier_idle02_guy01"][0] = %seo_injured_soldier_idle02_guy01;
	level.var_78A9["generic"]["seo_injured_soldier_idle02_guy02"][0] = %seo_injured_soldier_idle02_guy02;
	level.var_78A9["generic"]["seo_turn_gesturetomove_guy01"] = %seo_turn_gesturetomove_guy01;
	level.var_78A9["generic"]["seo_fob_drop_guy_01"] = %seo_fob_drop_guy_01;
	level.var_78A9["generic"]["seo_fob_drop_guy_02"] = %seo_fob_drop_guy_02;
	level.var_78A9["generic"]["seo_fob_drop_guy_03"] = %seo_fob_drop_guy_03;
	level.var_78A9["generic"]["seo_move_stoponradio_loop_guy1"] = %seo_move_stoponradio_loop_guy1;
	level.var_78A9["generic"]["seo_base_truck_with_mechs_guy"][0] = %seo_base_truck_with_mechs_guy;
	level.var_78A9["generic"]["seo_base_truck_with_mechs_guy1"][0] = %seo_base_truck_with_mechs_guy1;
	level.var_78A9["generic"]["seo_base_truck_with_mechs_guy2"][0] = %seo_base_truck_with_mechs_guy2;
	level.var_78A9["generic"]["seo_base_truck_with_mechs_guy3"][0] = %seo_base_truck_with_mechs_guy3;
	level.var_78A9["generic"]["seo_base_truck_with_mechs_guy4"][0] = %seo_base_truck_with_mechs_guy4;
	level.var_78A9["generic"]["SEO_walking_pointing_soldier_01"] = %seo_walking_pointing_soldier_01;
	level.var_78A9["generic"]["SEO_walking_pointing_soldier_02"] = %seo_walking_pointing_soldier_02;
	level.var_78A9["generic"]["SEO_walking_pointing_soldier_03"] = %seo_walking_pointing_soldier_03;
	level.var_78A9["generic"]["SEO_walking_pointing_soldier_04"] = %seo_walking_pointing_soldier_04;
	level.var_78A9["generic"]["seo_cover_launcher_idle_guy01"][0] = %seo_cover_launcher_idle_guy01;
	lib_A506::func_807("generic","fire",::func_3648,"seo_cover_launcher_idle_guy01");
	level.var_78A9["generic"]["seo_cover_launcher_idle_guy02"][0] = %seo_cover_launcher_idle_guy02;
	level.var_78A9["generic"]["seo_base_walk_with_crate_02_mech"][0] = %seo_base_walk_with_crate_02_mech;
	level.var_78A9["generic"]["seo_base_walk_with_crate_01_mech"][0] = %seo_base_walk_with_crate_01_mech;
	level.var_78A9["generic"]["cakewalk"] = %seo_base_walk_with_crate_01_mech;
	level.var_78A9["generic"]["mech_stand_idle_wbtest"][0] = %mech_stand_idle_wbtest;
	level.var_78A9["generic"]["mech_unaware_idle"][0] = %mech_unaware_idle;
	level.var_78A9["generic"]["mech_stand_reload"] = %mech_stand_reload;
	level.var_78A9["generic"]["mech_walkf"] = %mech_walkf;
	level.var_78A9["generic"]["mech_unaware_walk"] = %mech_unaware_walk;
	animscripts\utility::func_7FB9("vfx_mech_footstepfx_rf","J_Ball_RI",undefined,common_scripts\utility::getfx("footstep_mech"));
	animscripts\utility::func_7FB9("vfx_mech_footstepfx_lf","J_Ball_LE",undefined,common_scripts\utility::getfx("footstep_mech"));
	level.var_78A9["generic"]["laptop_idle"][0] = %laptop_stand_idle;
	level.var_78A9["generic"]["laptop_idle"][1] = %laptop_stand_idle_flinch;
	level.var_78A9["generic"]["laptop_idle"][2] = %laptop_stand_idle_focused;
	level.var_78A9["generic"]["laptop_idle_focused"][0] = %laptop_stand_idle_flinch;
	level.var_78A9["generic"]["laptop_idle_focused"][1] = %laptop_stand_idle_focused;
	level.var_78A9["generic"]["onlooking_guard"][0] = %readystand_idle;
	level.var_78A9["generic"]["onlooking_guard"][1] = %readystand_idle_twitch_1;
	level.var_78A9["generic"]["onlooking_guard"][2] = %readystand_idle_twitch_2;
	level.var_78A9["generic"]["onlooking_guard"][3] = %readystand_idle_twitch_3;
	level.var_78A9["generic"]["onlooking_guard"][4] = %readystand_idle_twitch_4;
	level.var_78A9["generic"]["binocular_loop"][0] = %blackout_binoc_idle;
	level.var_78A9["generic"]["radio_loop"][0] = %ny_manhattan_radio_talk_idle;
	level.var_78A9["generic"]["lag_lobby_waiting_elevator_loop_guy2"][0] = %lag_lobby_waiting_elevator_loop_guy2;
	level.var_78A9["generic"]["laptop_officer"][0] = %laptop_officer_idle;
	level.var_78A9["generic"]["laptop_officer"][1] = %laptop_officer_talk;
	level.var_78A9["generic"]["laptop_officer_idle"][0] = %laptop_officer_idle;
	level.var_78A9["generic"]["laptop_officer_talk"][0] = %laptop_officer_talk;
	level.var_78A9["generic"]["blackout_flashlightguy_death_only"] = %blackout_flashlightguy_death_only;
	level.var_78A9["generic"]["cargoship_stunned_clipboard_death"] = %cargoship_stunned_clipboard_death;
	level.var_78A9["generic"]["drone_stand_death"] = %drone_stand_death;
	level.var_78A9["generic"]["death_run_onfront"] = %death_run_onfront;
	level.var_78A9["generic"]["payback_escape_forward_wave_right_price"] = %payback_escape_forward_wave_right_price;
	level.var_78A9["generic"]["berlin_spotter_spot_idle"][0] = %berlin_spotter_spot_idle;
	level.var_78A9["generic"]["sniper_escape_spotter_idle"][0] = %sniper_escape_spotter_idle;
	level.var_78A9["generic"]["laptop_officer_idle"][0] = %laptop_officer_idle;
	level.var_78A9["generic"]["laptop_stand_idle"][0] = %laptop_stand_idle;
	level.var_78A9["generic"]["stealth_walk"][0] = %stealth_walk;
	level.var_78A9["cormack"]["exo_punch_stackup"] = %seo_hotel_stackup_guy1;
	level.var_78A9["cormack"]["exo_punch_stackup_idle"][0] = %seo_hotel_stackup_idle_guy1;
	level.var_78A9["cormack"]["seo_hotel_stackup_guy2"] = %seo_hotel_stackup_guy2;
	level.var_78A9["cormack"]["seo_hotel_stackup_idle_guy2"][0] = %seo_hotel_stackup_idle_guy2;
	level.var_78A9["cormack"]["exo_punch_breach"] = %seo_hotel_breach_guy1;
	level.var_78A9["cormack"]["exo_punch_idle"][0] = %seo_hotel_breach_idle_guy1;
	level.var_78A9["cormack"]["exo_punch_react"] = %seo_hotel_breach_rocketblast_guy1;
	level.var_78A9["cormack"]["seo_react_to_war_cormack"] = %seo_react_to_war_cormack;
	level.var_78A9["cormack"]["seo_react_to_war_run_npc1"] = %seo_react_to_war_run_npc2;
	level.var_78A9["cormack"]["seo_mall_sizeup_jump_cormack"] = %seo_mall_sizeup_jump_cormack;
	level.var_78A9["cormack"]["seo_mall_sizeup_jump_cormack_idle"][0] = %seo_mall_cormack_idle;
	level.var_78A9["cormack"]["cornerstndr_alert_signal_enemy_spotted"] = %cornerstndr_alert_signal_enemy_spotted;
	level.var_78B0["cormack"]["cornerstndr_alert_signal_enemy_spotted"] = 0.75;
	lib_A506::func_80F("cormack","shoot_glass","cormack_shot_glass","seo_mall_sizeup_jump_cormack");
	level.var_78A9["cormack"]["run_lowready_f"] = %run_lowready_f;
	lib_A506::func_807("cormack","cormack_jump_assist",::animscripts\traverse\boost::func_549B,"seo_mall_sizeup_jump_cormack");
	lib_A506::func_807("cormack","ambient_explo",::lib_A5CE::func_220E,"seo_mall_sizeup_jump_cormack");
	level.var_78A9["cormack"]["first_landassist_enter"] = %seo_pre_lassist_1st_jump_enter_npc1;
	level.var_78A9["cormack"]["first_landassist_idle"][0] = %seo_pre_lassist_1st_jump_idle_npc1;
	level.var_78A9["cormack"]["first_landassist_jump"] = %seo_pre_lassist_1st_jump_npc1;
	level.var_78A9["cormack"]["first_landassist_jump_e3"] = %seo_pre_lassist_1st_jump_npc1_e3;
	lib_A506::func_807("cormack","assist_thrusters",::animscripts\traverse\boost::func_549B,"first_landassist_jump");
	lib_A506::func_807("cormack","assist_thrusters",::animscripts\traverse\boost::func_549B,"first_landassist_jump_e3");
	lib_A506::func_807("cormack","landassist_jump_land",::animscripts\traverse\boost::func_549C,"first_landassist_jump_e3");
	level.var_78A9["jackson"]["first_landassist_jump_e3"] = %seo_pre_lassist_1st_jump_npc2_e3;
	lib_A506::func_807("jackson","assist_thrusters_2",::animscripts\traverse\boost::func_549B,"first_landassist_jump_e3");
	lib_A506::func_807("jackson","landassist_jump_land",::animscripts\traverse\boost::func_549C,"first_landassist_jump_e3");
	level.var_78A9["cormack"]["swarm_cover_cormack_into"] = %seo_drone_swarm_cover_guy1;
	level.var_78A9["cormack"]["swarm_cover_cormack"][0] = %seo_drone_swarm_cover_idle_guy1;
	level.var_78A9["jackson"]["swarm_cover_jackson_into"] = %seo_drone_swarm_cover_alt_guy1;
	level.var_78A9["jackson"]["swarm_cover_jackson"][0] = %seo_drone_swarm_cover_alt_idle_guy1;
	level.var_78A9["cormack"]["ny_manhattan_signal_flashbang_delta_start"] = %ny_manhattan_signal_flashbang_delta_start;
	level.var_78A9["cormack"]["ny_manhattan_signal_flashbang_delta_idlewall"] = %ny_manhattan_signal_flashbang_delta_idlewall;
	level.var_78A9["cormack"]["cormack_door_kick_start"] = %seo_door_kick_open_start_npc;
	level.var_78A9["cormack"]["cormack_door_kick_idle"][0] = %seo_door_kick_open_idle_npc;
	level.var_78A9["cormack"]["cormack_door_kick_end"] = %seo_door_kick_open_exit_npc;
	level.var_78A9["will_irons"]["seo_hotel_stackup_guy1"] = %seo_hotel_stackup_guy1;
	level.var_78A9["will_irons"]["seo_hotel_stackup_idle_guy1"][0] = %seo_hotel_stackup_idle_guy1;
	level.var_78A9["will_irons"]["exo_punch_stackup"] = %seo_hotel_stackup_guy2;
	level.var_78A9["will_irons"]["exo_punch_stackup_idle"][0] = %seo_hotel_stackup_idle_guy2;
	level.var_78A9["will_irons"]["exo_punch_breach"] = %seo_hotel_breach_guy2;
	level.var_78A9["will_irons"]["exo_punch_idle"][0] = %seo_hotel_breach_idle_guy2;
	level.var_78A9["will_irons"]["exo_punch_react"] = %seo_hotel_breach_rocketblast_guy2;
	level.var_78A9["will_irons"]["explosivebreach_v1_stackl_idle"][0] = %explosivebreach_v1_stackl_idle;
	level.var_78A9["will_irons"]["run_lowready_f"] = %run_lowready_f;
	level.var_78A9["will_irons"]["patrolstand_look"][0] = %patrolstand_look;
	level.var_78A9["will_irons"]["casual_stand_idle"][0] = %casual_stand_idle;
	level.var_78A9["will_irons"]["seo_react_to_war_poseA_idle"][0] = %seo_react_to_war_posea_idle;
	level.var_78A9["will_irons"]["seo_react_to_war_poseA_idle2"][0] = %seo_react_to_war_posea_idle2;
	level.var_78A9["will_irons"]["seo_react_to_war_poseA_idle3"][0] = %seo_react_to_war_posea_idle3;
	level.var_78A9["will_irons"]["seo_react_to_war_poseA_in"] = %seo_react_to_war_posea_in;
	level.var_78A9["will_irons"]["seo_react_to_war_poseA_out"] = %seo_react_to_war_posea_out;
	level.var_78A9["will_irons"]["seo_door_walk_enter_1"] = %seo_door_walk_enter_1;
	level.var_78A9["will_irons"]["seo_door_idle_twitch_shoot_will"] = %seo_door_idle_twitch_shoot_will;
	level.var_78A9["will_irons"]["will_door_shield_intro"] = %seo_door_slide_in_will;
	level.var_78A9["will_irons"]["will_door_shield_idle"][0] = %seo_door_idleb_loop_will;
	level.var_78A9["will_irons"]["will_door_shield_grab"] = %seo_door_grab_will;
	level.var_78A9["will_irons"]["will_door_shield_twitch"] = %seo_door_idle_twitch_wave_will;
	level.var_78A9["will_irons"]["will_door_shield_grab_idle"][0] = %seo_door_grab_idlea_loop_will;
	level.var_78A9["will_irons"]["will_door_shield_hold_idle"][0] = %seo_door_grab_hold_idle_will;
	level.var_78A9["will_irons"]["seo_door_grab_walk_forward"][0] = %seo_door_grab_walk_forward;
	level.var_78A9["will_irons"]["seo_door_idle_exit_1"][0] = %seo_door_idle_exit_1;
	level.var_78A9["will_irons"]["seo_door_walk_drop"] = %seo_door_walk_drop;
	level.var_78A9["will_irons"]["seo_react_to_war_will"] = %seo_react_to_war_will;
	level.var_78A9["will_irons"]["seo_react_to_war_run_npc2"] = %seo_react_to_war_run_npc1;
	level.var_78A9["will_irons"]["seo_mall_sizeup_jump_will"] = %seo_mall_sizeup_jump_will;
	lib_A506::func_807("will_irons","will_jump_assist",::animscripts\traverse\boost::func_549B,"seo_mall_sizeup_jump_will");
	lib_A506::func_807("will_irons","will_ambient_explo",::lib_A5CE::func_A31D,"seo_mall_sizeup_jump_will");
	lib_A506::func_80F("will_irons","swap_door","will_swap_door","will_door_shield_grab");
	level.var_78A9["will_irons"]["first_landassist_enter"] = %seo_pre_lassist_1st_jump_enter_npc2;
	level.var_78B0["will_irons"]["first_landassist_enter"] = 0.5;
	level.var_78A9["will_irons"]["first_landassist_idle"][0] = %seo_pre_lassist_1st_jump_idle_npc2;
	level.var_78A9["will_irons"]["first_landassist_jump"] = %seo_pre_lassist_1st_jump_npc2;
	level.var_78A9["will_irons"]["first_landassist_jump_e3"] = %seo_pre_lassist_1st_jump_npc2_e3;
	lib_A506::func_807("will_irons","assist_thrusters_2",::animscripts\traverse\boost::func_549B,"first_landassist_jump");
	lib_A506::func_807("will_irons","assist_thrusters_2",::animscripts\traverse\boost::func_549B,"first_landassist_jump_e3");
	lib_A506::func_807("will_irons","landassist_jump_land",::animscripts\traverse\boost::func_549C,"first_landassist_jump_e3");
	level.var_78A9["will_irons"]["truck_push_scene_enter"] = %seo_exo_move_obstacle_enter_npc;
	level.var_78A9["will_irons"]["truck_push_scene_idle_in"] = %seo_exo_move_obstacle_push_idle_in_npc;
	level.var_78A9["will_irons"]["truck_push_scene_idle_out"] = %seo_exo_move_obstacle_push_idle_out_npc;
	level.var_78A9["will_irons"]["truck_push_scene_move"] = %seo_exo_move_obstacle_push_npc;
	level.var_78A9["will_irons"]["truck_push_scene_idle"] = %seo_exo_move_obstacle_push_idle_npc;
	level.var_78A9["will_irons"]["truck_push_scene_idle_a"] = %seo_exo_move_obstacle_waiting_idle_a_npc;
	level.var_78A9["will_irons"]["truck_push_scene_idle_b"] = %seo_exo_move_obstacle_waiting_idle_b_npc;
	level.var_78A9["will_irons"]["truck_push_scene_idle_c"] = %seo_exo_move_obstacle_waiting_idle_c_npc;
	level.var_78A9["will_irons"]["truck_push_scene_idle_d"] = %seo_exo_move_obstacle_waiting_idle_d_npc;
	level.var_78A9["will_irons"]["rally_up_enter"] = %seo_checkconer_rally_up_enter;
	level.var_78A9["will_irons"]["rally_up_exit"] = %seo_checkconer_rally_up_exit;
	level.var_78A9["will_irons"]["rally_up_idle_a"] = %seo_checkconer_rally_up_idle_a;
	level.var_78A9["will_irons"]["rally_up_idle_b"] = %seo_checkconer_rally_up_idle_b;
	level.var_78A9["will_irons"]["rally_up_idle_c"] = %seo_checkconer_rally_up_idle_c;
	level.var_78A9["cormack"]["fob_meet_cormack"] = %seo_fob_sgt_brief_cormack;
	level.var_78A9["generic"]["fob_meet_guy1"] = %seo_fob_sgt_brief_guy1;
	level.var_78A9["daniels"]["fob_meet_guy2"] = %seo_fob_sgt_brief_guy2;
	level.var_78A9["generic"]["fob_meet_guy1_idle"][0] = %seo_fob_sgt_brief_idle_guy1;
	level.var_78A9["daniels"]["fob_meet_guy2_idle"][0] = %seo_fob_sgt_brief_idle_guy2;
	level.var_78A9["will_irons"]["fob_meet_will_into"] = %seo_react_to_war_run_2_right90_idle;
	level.var_78A9["cormack"]["fob_meet_post_enter_1"] = %seo_fob_postbrief_enter_idle_guy;
	level.var_78A9["will_irons"]["fob_meet_post_enter_2"] = %seo_fob_postbrief_enter_idle_guy1;
	level.var_78A9["cormack"]["fob_meet_post_exit_1"] = %seo_fob_postbrief_exit_idle_guy;
	level.var_78A9["will_irons"]["fob_meet_post_exit_2"] = %seo_fob_postbrief_exit_idle_guy1;
	level.var_78A9["cormack"]["fob_meet_post_idle_1"][0] = %seo_fob_postbrief_idle_guy;
	level.var_78A9["will_irons"]["fob_meet_post_idle_2"][0] = %seo_fob_postbrief_idle_guy1;
	lib_A506::func_80F("cormack","wave","fob_cormack_wave","fob_meet_cormack");
	level.var_78A9["cormack"]["missile_evade"] = %seo_hotel_escape_rockets_guy1;
	level.var_78A9["will_irons"]["missile_evade"] = %seo_hotel_escape_rockets_guy2;
	level.var_78A9["generic"]["drag_idle_1_guy_1"][0] = %seo_injured_soldier_idle01_guy01;
	level.var_78A9["generic"]["drag_idle_2_guy_1"][0] = %seo_injured_soldier_idle02_guy01;
	level.var_78A9["generic"]["drag_idle_1_guy_2"][0] = %seo_injured_soldier_idle01_guy02;
	level.var_78A9["generic"]["drag_idle_2_guy_2"][0] = %seo_injured_soldier_idle02_guy02;
	level.var_78A9["generic"]["drag_guy_save"] = %seo_injured_soldier_drag_guy01;
	level.var_78A9["generic"]["drag_guy_injured"] = %seo_injured_soldier_drag_guy02;
	level.var_78A9["generic"]["shotgunbreach_v1_stacka_runin"] = %shotgunbreach_v1_stacka_runin;
	level.var_78A9["generic"]["mulekick_kick"] = %ny_harbor_breech_mulekick_guy1_kick;
	level.var_78A9["generic"]["idle_at_door"][0] = %ny_harbor_breech_mulekick_guy1_idle;
	level.var_78A9["cormack"]["pod_phase1a"] = %seo_pod_drop_phase1a_cormack;
	level.var_78B0["cormack"]["pod_phase1a"] = 0;
	level.var_78A9["cormack"]["pod_phase1b"] = %seo_pod_drop_phase1b_cormack;
	level.var_78B0["cormack"]["pod_phase1b"] = 0;
	level.var_78A9["cormack"]["pod_phase2b"] = %seo_pod_phase2b_cormack;
	level.var_78B0["cormack"]["pod_phase2b"] = 0;
	level.var_78A9["cormack"]["pod_phase3"] = %seo_pod_phase3_cormack;
	level.var_78B0["cormack"]["pod_phase3"] = 0;
	level.var_78A9["cormack"]["pod_phase3_fail"] = %seo_pod_phase3_fail_cormack;
	level.var_78B0["cormack"]["pod_phase3_fail"] = 0.333;
	level.var_78A9["cormack"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_cormack;
	level.var_78B0["cormack"]["pod_phase4a_intro"] = 0;
	level.var_78A9["cormack"]["pod_phase4a"] = %seo_pod_phase4a_cormack;
	level.var_78B0["cormack"]["pod_phase4a"] = 0;
	level.var_78A9["cormack"]["pod_phase4b"] = %seo_pod_phase4b_cormack;
	level.var_78B0["cormack"]["pod_phase4b"] = 0;
	level.var_78A9["cormack"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_cormack;
	level.var_78A9["cormack"]["pod_phase5"] = %seo_pod_phase5_cormack;
	level.var_78A9["cormack"]["pod_wakeup"] = %seo_pod_crash_wake_up_cormack;
	level.var_78B0["cormack"]["pod_wakeup"] = 0;
	level.var_78A9["cormack"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_idle_cormack;
	level.var_78A9["jackson"]["pod_phase1a"] = %seo_pod_drop_phase1a_jackson;
	level.var_78B0["jackson"]["pod_phase1a"] = 0;
	level.var_78A9["jackson"]["pod_phase1b"] = %seo_pod_drop_phase1b_jackson;
	level.var_78B0["jackson"]["pod_phase1b"] = 0;
	level.var_78A9["jackson"]["pod_phase2b"] = %seo_pod_phase2b_jackson;
	level.var_78B0["jackson"]["pod_phase2b"] = 0;
	level.var_78A9["jackson"]["pod_phase3"] = %seo_pod_phase3_jackson;
	level.var_78B0["jackson"]["pod_phase3"] = 0;
	level.var_78A9["jackson"]["pod_phase3_fail"] = %seo_pod_phase3_fail_jackson;
	level.var_78B0["jackson"]["pod_phase3_fail"] = 0.333;
	level.var_78A9["jackson"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_jackson;
	level.var_78B0["jackson"]["pod_phase4a_intro"] = 0;
	level.var_78A9["jackson"]["pod_phase4a"] = %seo_pod_phase4a_jackson;
	level.var_78B0["jackson"]["pod_phase4a"] = 0;
	level.var_78A9["jackson"]["pod_phase4b"] = %seo_pod_phase4b_jackson;
	level.var_78B0["jackson"]["pod_phase4b"] = 0;
	level.var_78A9["jackson"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_jackson;
	level.var_78A9["jackson"]["pod_phase5"] = %seo_pod_phase5_jackson;
	level.var_78A9["jackson"]["pod_wakeup"] = %seo_pod_crash_wake_up_npc2;
	level.var_78B0["jackson"]["pod_wakeup"] = 0;
	level.var_78A9["jackson"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_idle_npc2;
	level.var_78B0["jackson"]["pod_wakeup_idle"] = 0;
	level.var_78A9["will_irons"]["pod_phase1a"] = %seo_pod_drop_phase1a_will;
	level.var_78B0["will_irons"]["pod_phase1a"] = 0;
	level.var_78A9["will_irons"]["pod_phase1b"] = %seo_pod_drop_phase1b_will;
	level.var_78B0["will_irons"]["pod_phase1b"] = 0;
	level.var_78A9["will_irons"]["pod_phase2b"] = %seo_pod_phase2b_will;
	level.var_78B0["will_irons"]["pod_phase2b"] = 0;
	level.var_78A9["will_irons"]["pod_phase3"] = %seo_pod_phase3_will;
	level.var_78B0["will_irons"]["pod_phase3"] = 0;
	level.var_78A9["will_irons"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_will;
	level.var_78B0["will_irons"]["pod_phase4a_intro"] = 0;
	level.var_78A9["will_irons"]["pod_phase4a"] = %seo_pod_phase4a_will;
	level.var_78B0["will_irons"]["pod_phase4a"] = 0;
	level.var_78A9["will_irons"]["pod_phase4b"] = %seo_pod_phase4b_will;
	level.var_78B0["will_irons"]["pod_phase4b"] = 0;
	level.var_78A9["will_irons"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_will;
	level.var_78A9["will_irons"]["pod_phase5"] = %seo_pod_phase5_will;
	level.var_78A9["will_irons"]["pod_wakeup"] = %seo_pod_crash_wake_up_will;
	level.var_78B0["will_irons"]["pod_wakeup"] = 0;
	level.var_78A9["will_irons"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_idle_will;
	level.var_78B0["will_irons"]["pod_wakeup_idle"] = 0;
	level.var_78A9["cormack"]["pod_exit"] = %seo_pod_exit_cormac;
	level.var_78B0["cormack"]["pod_exit"] = 0;
	lib_A506::func_807("cormack","vfx_cormack_exit_pod_start",::lib_A5CE::func_2211,"pod_exit");
	level.var_78A9["cormack"]["pod_exit_outro"] = %seo_pod_exit_cormac_into_cqb;
	level.var_78A9["will_irons"]["pod_exit"] = %seo_pod_exit_will;
	level.var_78B0["will_irons"]["pod_exit"] = 0;
	level.var_78A9["will_irons"]["pod_exit_outro"] = %seo_pod_exit_will_into_cqb;
	level.var_78A9["new_guy"]["pod_exit"] = %seo_pod_exit_npc1;
	level.var_78B0["new_guy"]["pod_exit"] = 0;
	level.var_78A9["new_guy"]["pod_exit_outro"] = %seo_pod_exit_npc1_into_cqb;
	level.var_78A9["jackson"]["pod_exit"] = %seo_pod_exit_npc2;
	level.var_78B0["jackson"]["pod_exit"] = 0;
	level.var_78A9["jackson"]["pod_exit_outro"] = %seo_pod_exit_npc2_into_cqb;
	level.var_78A9["cormack"]["pod_exit_idle"][0] = %seo_pod_exit_cormac_idle_loop;
	level.var_78A9["will_irons"]["pod_exit_idle"][0] = %seo_pod_exit_will_idle_loop;
	level.var_78A9["new_guy"]["pod_exit_idle"][0] = %seo_pod_exit_npc2_idle_loop;
	level.var_78A9["jackson"]["pod_exit_idle"][0] = %seo_pod_exit_npc2_idle_loop;
	level.var_78A9["jackson"]["seo_react_to_war_run_npc2"] = %seo_react_to_war_run_npc2;
	level.var_78A9["generic"]["pod_exit_1"] = %hms_greece_traverse_jumpdown96_01;
	level.var_78A9["generic"]["pod_exit_2"] = %hms_greece_traverse_jumpdown96_02;
	level.var_78A9["generic"]["crouch_cover_stand_aim_down"][0] = %crouch_cover_stand_aim_down;
	level.var_78A9["generic"]["sanfran_b_intro_burke_idle"][0] = %sanfran_b_intro_burke_idle;
	level.var_78A9["generic"]["crouch_cover_stand_aim_down_single"] = %crouch_cover_stand_aim_down;
	level.var_78A9["generic"]["sanfran_b_intro_burke_idle_single"] = %sanfran_b_intro_burke_idle;
	level.var_78A9["generic"]["so_hijack_execution_aim_down_idle_terrorist_single"] = %so_hijack_execution_aim_down_idle_terrorist;
	level.var_78A9["generic"]["seo_jumpdown_takedown_guy1"] = %seo_jumpdown_takedown_guy1;
	level.var_78A9["generic"]["seo_jumpdown_takedown_guy2"] = %seo_jumpdown_takedown_guy2;
	level.var_78A9["generic"]["coup_talking_patrol_guy2"][0] = %coup_talking_patrol_guy2;
	level.var_78A9["generic"]["coup_talking_patrol_guy1"][0] = %coup_talking_patrol_guy1;
	level.var_78A9["generic"]["sitting_guard_loadak_idle"][0] = %sitting_guard_loadak_idle;
	level.var_78A9["generic"]["seo_giveorders_idle_guy01"][0] = %seo_giveorders_idle_guy01;
	level.var_78A9["generic"]["casual_stand_idle"][0] = %casual_stand_idle;
	level.var_78A9["generic"]["patrol_bored_idle"][0] = %patrol_bored_idle;
	level.var_78A9["generic"]["patrolwalk_cold_huddle_stand_idle"][0] = %patrolwalk_cold_huddle_stand_idle;
	level.var_78A9["generic"]["patrolstand_look"] = %patrolstand_look;
	level.var_78A9["generic"]["patrolstand_idle"][0] = %patrolstand_idle;
	level.var_78A9["generic"]["patrolstand_twitch"] = %patrolstand_twitch;
	level.var_78A9["generic"]["det_camp_intro_idle_guy3"][0] = %det_camp_intro_idle_guy3;
	level.var_78A9["generic"]["fusion_security_doors_idle_guy1"][0] = %fusion_security_doors_idle_guy1;
	level.var_78A9["generic"]["fusion_security_doors_idle_guy2"][0] = %fusion_security_doors_idle_guy2;
	level.var_78A9["generic"]["seo_fob_soldier_standing_idle_guy01"][0] = %seo_fob_soldier_standing_idle_guy01;
	level.var_78A9["generic"]["seo_standing_soldier_idle_01"][0] = %seo_standing_soldier_idle_01;
	level.var_78A9["generic"]["seo_standing_soldier_idle_02"][0] = %seo_standing_soldier_idle_02;
	level.var_78A9["generic"]["seo_standing_soldier_idle_01_single"] = %seo_standing_soldier_idle_01;
	level.var_78A9["generic"]["seo_standing_soldier_idle_02_single"] = %seo_standing_soldier_idle_02;
	level.var_78A9["generic"]["run_lowready_f"] = %run_lowready_f;
	level.var_3958 = ["patrolstand_look","patrolstand_idle","patrolstand_twitch"];
	level.var_3957 = ["casual_stand_idle","patrol_bored_idle","patrolwalk_cold_huddle_stand_idle","seo_fob_soldier_standing_idle_guy01","seo_standing_soldier_idle_01","seo_standing_soldier_idle_02"];
	level.var_78A9["generic"]["gi_pose_gideon"] = %gi_gideon;
	level.var_78A9["generic"]["gi_pose_mech"] = %gi_mech;
	level.var_78A9["generic"]["lab_corner_check_right_exit"] = %lab_corner_check_right_exit;
	level.var_78A9["generic"]["lab_corner_check_right_into"] = %lab_corner_check_right_into;
	level.var_78A9["generic"]["lab_corner_check_right_loop"][0] = %lab_corner_check_right_loop;
	level.var_78A9["generic"]["det_corner_check_left_enter"] = %det_corner_check_left_enter;
	level.var_78A9["generic"]["det_corner_check_left_exit"] = %det_corner_check_left_exit;
	level.var_78A9["generic"]["det_corner_check_left_loop"][0] = %det_corner_check_left_loop;
	level.var_78A9["generic"]["det_corner_check_right_into"] = %det_corner_check_right_into;
	level.var_78A9["generic"]["det_corner_check_right_exit"] = %det_corner_check_right_exit;
	level.var_78A9["generic"]["det_corner_check_right_loop"][0] = %det_corner_check_right_loop;
	level.var_78A9["cormack"]["seo_react_to_war_idle"][0] = %seo_react_to_war_idle;
	level.var_78A9["cormack"]["seo_react_to_war_idle_2_run"] = %seo_react_to_war_idle_2_run;
	level.var_78A9["cormack"]["seo_react_to_war_idle_2_walk"] = %seo_react_to_war_idle_2_walk;
	level.var_78A9["cormack"]["seo_react_to_war_run_2_idle"] = %seo_react_to_war_run_2_idle;
	level.var_78A9["cormack"]["seo_react_to_war_walk"] = %seo_react_to_war_walk;
	level.var_78A9["cormack"]["seo_react_to_war_walk_2_idle"] = %seo_react_to_war_walk_2_idle;
	level.var_78A9["will_irons"]["seo_react_to_war_idle"][0] = %seo_react_to_war_idle;
	level.var_78A9["will_irons"]["seo_react_to_war_idle_2_run"] = %seo_react_to_war_idle_2_run;
	level.var_78A9["will_irons"]["seo_react_to_war_idle_2_walk"] = %seo_react_to_war_idle_2_walk;
	level.var_78A9["will_irons"]["seo_react_to_war_run_2_idle"] = %seo_react_to_war_run_2_idle;
	level.var_78A9["will_irons"]["seo_react_to_war_walk"] = %seo_react_to_war_walk;
	level.var_78A9["will_irons"]["seo_react_to_war_walk_2_idle"] = %seo_react_to_war_walk_2_idle;
	level.var_78AE["mech_model"] = #animtree;
	level.var_78B2["mech_model"] = "npc_exo_armor_base";
	level.var_78A9["mech_model"]["seo_base_truck_with_mechs_mech"][0] = %seo_base_truck_with_mechs_mech;
	level.var_78A9["mech_model"]["seo_base_truck_with_mechs_mech1"][0] = %seo_base_truck_with_mechs_mech1;
	level.var_78A9["mech_model"]["seo_base_truck_with_mechs_mech2"][0] = %seo_base_truck_with_mechs_mech2;
	if(level.nextgen)
	{
		anim.var_39B0 = 1;
	}
}

//Function Number: 2
func_6A58()
{
	level.var_78AE["player_rig"] = #animtree;
	level.var_78B2["player_rig"] = "viewbody_marines_mitchell";
	level.var_78AE["player_arms"] = #animtree;
	level.var_78B2["player_arms"] = "worldhands_marines_mitchell";
	level.var_78A9["player_arms"]["gi_pose"] = %gi_camera;
	level.var_78A9["player_rig"]["land_assist_legs"] = %seo_land_assist_vm;
	level.var_78A9["player_rig"]["exo_punch_breach"] = %seo_hotel_breach_vm;
	level.var_78A9["player_rig"]["truck_push_scene_move"] = %seo_exo_move_obstacle_push_vm;
	level.var_78A9["player_rig"]["doorshield_ripoff"] = %vm_doorshield_pullout_viewbody;
	level.var_78A9["player_rig"]["pod_phase1a"] = %seo_pod_drop_phase1a_vm;
	level.var_78B0["player_rig"]["pod_phase1a"] = 0;
	level.var_78A9["player_rig"]["pod_phase1b"] = %seo_pod_drop_phase1b_vm;
	level.var_78B0["player_rig"]["pod_phase1b"] = 0;
	level.var_78A9["player_rig"]["pod_phase2b"] = %seo_pod_phase2b_vm;
	level.var_78B0["player_rig"]["pod_phase2b"] = 0;
	level.var_78A9["player_rig"]["pod_phase3"] = %seo_pod_phase3_vm;
	level.var_78B0["player_rig"]["pod_phase3"] = 0;
	level.var_78A9["player_rig"]["pod_phase3_fail"] = %seo_pod_phase3_fail_vm;
	level.var_78B0["player_rig"]["pod_phase3_fail"] = 0.333;
	level.var_78A9["player_rig"]["pod_phase3_rel_tag"] = %seo_pod_phase3_vm_rel_tag;
	level.var_78A9["player_rig"]["pod_phase3_grab_add"] = %seo_pod_phase3_vm_add;
	level.var_78A9["player_rig"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_vm;
	level.var_78B0["player_rig"]["pod_phase4a_intro"] = 0;
	level.var_78A9["player_rig"]["pod_phase4a"] = %seo_pod_phase4a_vm;
	level.var_78B0["player_rig"]["pod_phase4a"] = 0;
	level.var_78A9["player_rig"]["pod_phase4b"] = %seo_pod_phase4b_vm;
	level.var_78B0["player_rig"]["pod_phase4b"] = 0;
	level.var_78A9["player_rig"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_vm;
	level.var_78A9["player_rig"]["pod_phase5"] = %seo_pod_phase5_vm;
	level.var_78A9["player_rig"]["pod_exit"] = %seo_pod_exit_vm;
	level.var_78B0["player_rig"]["pod_exit"] = 0;
	level.var_78A9["player_rig"]["pod_wakeup"] = %seo_pod_crash_wake_up_vm;
	level.var_78B0["player_rig"]["pod_wakeup"] = 0;
	level.var_78A9["player_rig"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_idle_vm;
	level.var_78B0["player_rig"]["pod_wakeup_idle"] = 0;
	level.var_78A9["player_rig"]["pod_wakeup_right_1"] = %seo_pod_exit_unlock_right_1st_vm;
	level.var_78A9["player_rig"]["pod_wakeup_right_1_idle"][0] = %seo_pod_exit_unlock_right_1st_idle_vm;
	level.var_78A9["player_rig"]["pod_wakeup_right_2"] = %seo_pod_exit_unlock_right_2nd_vm;
	level.var_78A9["player_rig"]["pod_wakeup_left_2"] = %seo_pod_exit_unlock_left_2nd_vm;
	level.var_78A9["player_rig"]["pod_wakeup_left_1"] = %seo_pod_exit_unlock_left_1st_vm;
	level.var_78A9["player_rig"]["pod_wakeup_left_1_idle"][0] = %seo_pod_exit_unlock_left_1st_idle_vm;
	level.var_78A9["player_rig"]["pod_wakeup_kick_idle"][0] = %seo_pod_exit_door_kick1_idle_vm;
	lib_A506::func_807("player_rig","vfx_vm_exit_pod_start",::lib_A5CE::func_9DF0,"pod_exit");
	lib_A506::func_80F("player_rig","drop_pod_finish","drop_pod_finish","pod_exit");
	level.var_78A9["player_rig"]["missile_evade_1"] = %seo_hotel_escape_rockets_pt1_vm;
	level.var_78A9["player_rig"]["missile_evade_fail"] = %seo_hotel_escape_rockets_pt2_fail_vm;
	level.var_78A9["player_rig"]["missile_evade_success"] = %seo_hotel_escape_rockets_pt2_vm;
	lib_A506::func_80F("player_rig","fov_start","droppod_fov_change_start","pod_phase4b_crash");
	lib_A506::func_80F("player_rig","fov_start","droppod_fov_change_start","pod_phase5");
	lib_A506::func_80F("player_rig","fov_end","droppod_fov_change_end","pod_phase4b_crash");
	lib_A506::func_80F("player_rig","fov_end","droppod_fov_change_end","pod_phase5");
	lib_A506::func_807("player_rig","fov_screen",::maps\seoul_code_drop_pod::func_39FD);
	lib_A506::func_807("player_rig","fov_face",::maps\seoul_code_drop_pod::func_39F6);
	lib_A506::func_807("player_rig","door_rip",::lib_A5CE::func_1B6C,"doorshield_ripoff");
	level.var_78A9["player_arms"]["doorshield_ripoff_vm"] = %vm_doorshield_pullout_viewarms;
	level.var_78A9["player_rig"]["seo_meet_atlas"] = %seo_meet_atlas_vm;
	lib_A506::func_807("player_rig","fov_start",::maps\seoul_code_shopping_district::func_8F99,"seo_meet_atlas");
	lib_A506::func_807("player_rig","fov_end",::maps\seoul_code_shopping_district::func_8F98,"seo_meet_atlas");
	lib_A506::func_807("droppod","vfx_sinkhole_effect",::lib_A5CE::func_4F6F,"pod_phase2b");
	lib_A506::func_807("droppod","vfx_sinkhole_effect",::lib_A5CE::func_4F6F,"pod_phase3");
	level.var_78A9["player_arms"]["seo_canal_debrief_scanning_intro_vm"] = %seo_canal_debrief_scanning_intro_vm;
	level.var_78A9["player_arms"]["seo_canal_debrief_scanning_demoteam_loop_vm"][0] = %seo_canal_debrief_scanning_demoteam_loop_vm;
	level.var_78A9["player_arms"]["seo_canal_debrief_scanning_platform_to_demoteam_vm"] = %seo_canal_debrief_scanning_platform_to_demoteam_vm;
	level.var_78A9["player_arms"]["seo_canal_debrief_scanning_platform_loop_vm"][0] = %seo_canal_debrief_scanning_platform_loop_vm;
	level.var_78A9["player_arms"]["seo_canal_debrief_scanning_start_loop_vm"][0] = %seo_canal_debrief_scanning_start_loop_vm;
	level.var_78A9["player_arms"]["seo_canal_debrief_scanning_outro_vm"] = %seo_canal_debrief_scanning_outro_vm;
	level.var_78A9["player_arms"]["seo_canal_debrief_scanning_vm"] = %seo_canal_debrief_scanning_vm;
	level.var_78A9["player_rig"]["finale_plantbomb"] = %seo_finale_plantbomb_vm;
	level.var_78A9["player_rig"]["finale_pt02"] = %seo_finale_part2_vm;
	level.var_78A9["player_rig"]["finale_pt03"] = %seo_finale_phase2_silo_collapse_vm_pt03;
	lib_A506::func_807("player_rig","fov_change",::maps\seoul_code_shopping_district::func_1A7D,"finale_plantbomb");
	lib_A506::func_807("player_rig","fov_change_65",::maps\seoul_code_shopping_district::func_1A7C,"finale_pt02");
	lib_A506::func_807("player_rig","fov_change_55",::maps\seoul_code_shopping_district::func_1A7D,"finale_pt02");
	lib_A506::func_807("player_rig","shellshock_start",::maps\seoul_code_shopping_district::func_1A81,"finale_pt02");
	lib_A506::func_807("player_rig","rumble",::maps\seoul_code_shopping_district::func_1A7E,"finale_pt02");
	lib_A506::func_807("player_rig","rumble_sm",::maps\seoul_code_shopping_district::func_1A7F,"finale_pt02");
	lib_A506::func_807("player_rig","rumble",::maps\seoul_code_shopping_district::func_1A7E,"finale_pt03");
	lib_A506::func_807("player_rig","rumble_sm",::maps\seoul_code_shopping_district::func_1A7F,"finale_pt03");
	lib_A506::func_807("player_rig","drag_sand_begin",::lib_A5CE::func_65CD,"finale_pt03");
	level.var_78AE["player_dismembered_arm"] = #animtree;
	level.var_78B2["player_dismembered_arm"] = "vb_marines_dismember";
	level.var_78A9["player_dismembered_arm"]["finale_pt03"] = %seo_finale_phase2_silo_collapse_vm_arm;
}

//Function Number: 3
func_9C83()
{
	level.var_78AE["warbird"] = #animtree;
	level.var_78A9["warbird"]["warbird_door_l_open"] = %warbird_door_l_open;
	level.var_78A9["warbird"]["warbird_door_r_open"] = %warbird_door_r_open;
	level.var_78A9["warbird"]["warbird_open_idle"][0] = %warbird_open_idle;
	level.var_78AE["pickup"] = #animtree;
	level.var_78A9["pickup"]["pickup_tankcrush_front"] = %pickup_tankcrush_front;
	level.var_78AE["sedan"] = #animtree;
	level.var_78A9["sedan"]["sedan_tankcrush_side"] = %sedan_tankcrush_side;
	level.var_78AE["walker_tank"] = #animtree;
	level.var_78B2["walker_tank"] = "vehicle_walker_tank";
	level.var_78A9["walker_tank"]["walker_step_over"] = %seo_walker_intro_walker;
	level.var_78A9["walker_tank"]["walker_step_idle_1"][0] = %seo_walker_intro_idle_walker;
	level.var_78A9["walker_tank"]["walker_step_idle_2"][0] = %seo_walker_intro_idle1_walker;
	level.var_78A9["walker_tank"]["walker2_walking"] = %seo_walker_intro_walker2;
	level.var_78A9["walker_tank"]["walker2_idling"][0] = %seo_walker_intro_idle_walker2;
	level.var_78A9["walker_tank"]["gi_pose"] = %gi_walkingtank;
	lib_A506::func_807("walker_tank","vfx_tread_impact_FR",::lib_A5CE::func_938C,"walker_step_over");
	lib_A506::func_807("walker_tank","vfx_tread_impact_FL",::lib_A5CE::func_938B,"walker_step_over");
	lib_A506::func_807("walker_tank","vfx_tread_impact_RR",::lib_A5CE::func_938E,"walker_step_over");
	lib_A506::func_807("walker_tank","vfx_tread_impact_RL",::lib_A5CE::func_938D,"walker_step_over");
	level.var_78AE["door_grab_suv"] = #animtree;
	level.var_78A9["door_grab_suv"]["seo_door_slide_in_suv"] = %seo_door_slide_in_suv;
	level.var_78A9["door_grab_suv"]["seo_door_grab_suv"] = %seo_door_grab_suv;
	lib_A506::func_807("door_grab_suv","fx_ripdoor",::lib_A5CE::func_1B6D,"seo_door_grab_suv");
	level.var_78AE["weapon_platform"] = #animtree;
	level.var_78A9["weapon_platform"]["finale_pt01"] = %seo_finale_runup_weapon_platform;
	level.var_78A9["weapon_platform"]["finale_plantbomb"] = %seo_finale_plantbomb_weapon_platform;
	lib_A506::func_807("weapon_platform","door_close",::lib_A5CE::func_7D33,"finale_plantbomb");
	level.var_78A9["weapon_platform"]["finale_pt02"] = %seo_finale_part2_weapon_platform;
	lib_A506::func_807("weapon_platform","vfx_wp_take_off_start",::lib_A5CE::func_7D31,"finale_pt02");
	lib_A506::func_807("weapon_platform","vfx_wp_first_explo",::lib_A5CE::func_7D2C,"finale_pt02");
	level.var_78A9["weapon_platform"]["firing_loop"] = %seo_finale_firing_weapon_platform;
	lib_A506::func_807("weapon_platform","fire_cannon_1",::lib_A5CE::func_A2C2,"firing_loop");
	lib_A506::func_807("weapon_platform","fire_cannon_2",::lib_A5CE::func_A2C3,"firing_loop");
	lib_A506::func_807("weapon_platform","fire_cannon_3",::lib_A5CE::func_A2C4,"firing_loop");
	level.var_78AE["warbird_finale"] = #animtree;
	level.var_78A9["warbird_finale"]["finale_pt03"] = %seo_finale_phase2_warbird;
	level.var_78AE["truck_push"] = #animtree;
	level.var_78A9["truck_push"]["truck_push_scene_move"] = %seo_exo_move_obstacle_push_truck;
	level.var_78AE["droppod"] = #animtree;
	level.var_78A9["droppod"]["pod_exit"] = %seo_pod_exit_pod;
	level.var_78B0["droppod"]["pod_exit"] = 0;
	lib_A506::func_807("droppod","vfx_player_pod_door_kick",::lib_A5CE::func_6AE1,"pod_exit");
	lib_A506::func_807("droppod","vfx_drop_pod_fall_start",::lib_A5CE::func_2F54,"pod_exit");
	lib_A506::func_80F("droppod","pod_fall_start","droppod_begin_fall","pod_exit");
	lib_A506::func_80F("droppod","pod_swap","pod_swap_pod","pod_exit");
	level.var_78A9["droppod"]["pod_phase1a"] = %seo_pod_drop_phase1a_pod;
	level.var_78B0["droppod"]["pod_phase1a"] = 0;
	lib_A506::func_807("droppod","pod_door_close",::maps\seoul_code_drop_pod::func_2F4F,"pod_phase1a");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase1a");
	level.var_78A9["droppod"]["pod_phase1b"] = %seo_pod_drop_phase1b_pod;
	lib_A506::func_807("droppod","main_pod_jets",::lib_A5CE::func_58FA,"pod_phase1b");
	level.var_78B0["droppod"]["pod_phase1b"] = 0;
	lib_A506::func_80F("droppod","screen_intialize","screen_intialize","pod_phase1b");
	level.var_78A9["droppod"]["pod_phase2b"] = %seo_pod_phase2b_pod;
	level.var_78B0["droppod"]["pod_phase2b"] = 0;
	lib_A506::func_807("droppod","vfx_cloud_cover_start",::lib_A5CE::func_359B,"pod_phase2b");
	lib_A506::func_807("droppod","vfx_cloud_cover_end",::lib_A5CE::func_359A,"pod_phase2b");
	lib_A506::func_807("droppod","vfx_sinkhole_effect",::lib_A5CE::func_4F6F,"pod_phase2b");
	lib_A506::func_807("droppod","vfx_missile_pod_hit",::lib_A5CE::func_4F43,"pod_phase3");
	level.var_78A9["droppod"]["pod_phase3"] = %seo_pod_phase3_pod;
	level.var_78B0["droppod"]["pod_phase3"] = 0;
	level.var_78A9["droppod"]["pod_phase3_fail"] = %seo_pod_phase3_fail_pod;
	level.var_78B0["droppod"]["pod_phase3_fail"] = 0.333;
	lib_A506::func_80C("droppod","door_pop","door_pop");
	lib_A506::func_80C("droppod","door_shut","door_shut");
	lib_A506::func_807("droppod","vfx_missile_pod_hit",::lib_A5CE::func_4F50,"pod_phase3");
	lib_A506::func_807("droppod","door_shut",::lib_A5CE::func_4F52,"pod_phase3");
	level.var_78A9["droppod"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_pod;
	level.var_78B0["droppod"]["pod_phase4a_intro"] = 0;
	level.var_78A9["droppod"]["pod_phase4a"] = %seo_pod_phase4a_pod;
	level.var_78B0["droppod"]["pod_phase4a"] = 0;
	level.var_78A9["droppod"]["pod_wakeup"] = %seo_pod_crash_wake_up_pod;
	level.var_78B0["droppod"]["pod_wakeup"] = 0;
	level.var_78A9["droppod"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_idle_pod;
	level.var_78B0["droppod"]["pod_wakeup_idle"] = 0;
	lib_A506::func_807("droppod","vfx_pod_hit_apartment",::lib_A5CE::func_4F55,"pod_wakeup");
	lib_A506::func_807("droppod","vfx_pod_hit_building1",::lib_A5CE::func_4F57,"pod_phase4a");
	lib_A506::func_807("droppod","vfx_pod_hit_building1_floor1",::lib_A5CE::func_4F58,"pod_phase4a");
	lib_A506::func_807("droppod","vfx_pod_hit_building1_floor3",::lib_A5CE::func_4F5A);
	level.var_78A9["droppod"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_pod;
	level.var_78A9["droppod"]["pod_phase4b"] = %seo_pod_phase4b_pod;
	level.var_78B0["droppod"]["pod_phase4b"] = 0;
	lib_A506::func_807("droppod","vfx_pod_exit_building1",::lib_A5CE::func_4F54,"pod_phase4b");
	lib_A506::func_807("droppod","vfx_pod_hit_building2",::lib_A5CE::func_4F56,"pod_phase4b");
	lib_A506::func_80F("droppod","vfx_pod_hit_building2","building_2_crash","pod_phase4b");
	level.var_78A9["droppod"]["pod_phase5"] = %seo_pod_phase5_pod;
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase1a");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase1b");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase2b");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase3");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase4a");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase4a_intro");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase4b");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase4b_crash");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_phase5");
	lib_A506::func_80F("droppod","rumble","droppod_rumble","pod_exit");
	lib_A506::func_80F("droppod","rumble_constant_start","droppod_rumble_start","pod_phase3");
	lib_A506::func_80F("droppod","rumble_constant_end","droppod_rumble_end","pod_phase3");
	lib_A506::func_807("droppod","screen_on_chrome_abber",::maps\seoul_code_drop_pod::func_2F59);
	lib_A506::func_807("droppod","screen_off_damage_state",::maps\seoul_code_drop_pod::func_2F5C);
	lib_A506::func_807("droppod","screen_boot_up",::maps\seoul_code_drop_pod::func_2F58);
	lib_A506::func_807("droppod","screen_on_warning",::maps\seoul_code_drop_pod::func_2F5E);
	lib_A506::func_807("droppod","screen_glitch_warning",::maps\seoul_code_drop_pod::func_2F5A);
	lib_A506::func_807("droppod","screen_off",::maps\seoul_code_drop_pod::func_2F5B);
	lib_A506::func_80F("droppod","hide_floor1","pod_crash_hide_floor1","pod_phase4a");
	lib_A506::func_80F("droppod","hide_floor2","pod_crash_hide_floor2","pod_phase4a");
	lib_A506::func_80F("droppod","hide_floor3","pod_crash_hide_floor3","pod_phase4a");
	lib_A506::func_80F("droppod","hide_floor4","pod_crash_hide_floor4","pod_phase4a");
	level.var_78AE["droppod1"] = #animtree;
	level.var_78A9["droppod1"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod01;
	level.var_78A9["droppod1"]["pod_phase2b"] = %seo_pod_phase2b_pod01;
	level.var_78AE["droppod2"] = #animtree;
	level.var_78A9["droppod2"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod02;
	level.var_78A9["droppod2"]["pod_phase2b"] = %seo_pod_phase2b_pod02;
	lib_A506::func_807("droppod2","vfx_bottom_pod_thruster",::lib_A5CE::func_4EF3,"pod_phase1b");
	level.var_78AE["droppod3"] = #animtree;
	level.var_78A9["droppod3"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod03;
	level.var_78A9["droppod3"]["pod_phase2b"] = %seo_pod_phase2b_pod03;
	level.var_78AE["droppod4"] = #animtree;
	level.var_78A9["droppod4"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod04;
	lib_A506::func_807("droppod4","vfx_pod_spin",::lib_A5CE::func_2F82,"pod_phase1b");
	level.var_78A9["droppod4"]["pod_phase2b"] = %seo_pod_phase2b_pod04;
	level.var_78AE["droppod5"] = #animtree;
	level.var_78A9["droppod5"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod05;
	lib_A506::func_807("droppod5","vfx_pod_spin",::lib_A5CE::func_2F86,"pod_phase1b");
	level.var_78A9["droppod5"]["pod_phase2b"] = %seo_pod_phase2b_pod05;
	level.var_78AE["droppod6"] = #animtree;
	level.var_78A9["droppod6"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod06;
	level.var_78A9["droppod6"]["pod_phase2b"] = %seo_pod_phase2b_pod06;
	level.var_78AE["droppod8"] = #animtree;
	level.var_78A9["droppod8"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod08;
	level.var_78AE["droppod9"] = #animtree;
	level.var_78A9["droppod9"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod09;
	level.var_78AE["droppod10"] = #animtree;
	level.var_78A9["droppod10"]["pod_phase1b"] = %seo_pod_drop_phase1b_npc_pod10;
	level.var_78AE["blimp"] = #animtree;
	level.var_78B2["blimp"] = "vehicle_mil_blimp_ai";
	level.var_78A9["blimp"]["pod_phase1b"] = %seo_pod_drop_phase1b_blimp_main;
	lib_A506::func_807("blimp","vfx_blimp_explode",::lib_A5CE::func_4EEB,"pod_phase1b");
	lib_A506::func_807("blimp","Vfx_pod_blimp_detach01",::lib_A5CE::func_4F0F,"pod_phase1b");
	lib_A506::func_807("blimp","vfx_pod_blimp_detach02",::lib_A5CE::func_4F10,"pod_phase1b");
	level.var_78AE["blimp_main_01"] = #animtree;
	level.var_78B2["blimp_main_01"] = "vehicle_mil_blimp_ai";
	level.var_78A9["blimp_main_01"]["pod_phase1b"] = %seo_pod_drop_phase1b_blimp_main01;
	level.var_78AE["blimp_main_02"] = #animtree;
	level.var_78B2["blimp_main_02"] = "vehicle_mil_blimp_ai";
	level.var_78A9["blimp_main_02"]["pod_phase1b"] = %seo_pod_drop_phase1b_blimp_main02;
	level.var_78AE["blimp_main_03"] = #animtree;
	level.var_78B2["blimp_main_03"] = "vehicle_mil_blimp_ai";
	level.var_78A9["blimp_main_03"]["pod_phase1b"] = %seo_pod_drop_phase1b_blimp_main03;
	level.var_78AE["blimp_main_04"] = #animtree;
	level.var_78B2["blimp_main_04"] = "vehicle_mil_blimp_ai";
	level.var_78A9["blimp_main_04"]["pod_phase1b"] = %seo_pod_drop_phase1b_blimp_main04;
	lib_A506::func_80F("droppod","pod_door_deform_swap","pod_deform","pod_exit");
	lib_A506::func_80F("droppod","pod_door_deform_swap","pod_deform","pod_phase4b_crash");
	lib_A506::func_80F("droppod","pod_door_deform_swap","pod_deform","pod_phase5");
	level.var_78AE["npc_droppod"] = #animtree;
	level.var_78B2["npc_droppod"] = "vehicle_mil_drop_pod_opimized";
	level.var_78A9["npc_droppod"]["pod_landing"] = %seo_fob_drop_pod_01;
	lib_A506::func_807("npc_droppod","vfx_pod_impact",::lib_A5CE::func_2F55,"pod_landing");
	lib_A506::func_807("npc_droppod","drop_pod_thruster",::maps\seoul_code_gangnam::func_5DF2,"pod_landing");
	lib_A506::func_80F("npc_droppod","drop_pod_thruster","npc_pod_landed","pod_landing");
	lib_A506::func_807("truck_push","footstep_left_small",::lib_A5CE::func_34F9,"truck_push_scene_move");
	level.var_78AE["truck_explode_01"] = #animtree;
	level.var_78B2["truck_explode_01"] = "vehicle_civ_pickup_truck_01_wrecked";
	level.var_78A9["truck_explode_01"]["truck_explode"] = %fusion_vehicle_explode_truck;
	level.var_78AE["car_explode_01"] = #animtree;
	level.var_78B2["car_explode_01"] = "vehicle_civ_pickup_truck_01_wrecked";
	level.var_78A9["car_explode_01"]["car_explode"] = %sedan_crash_roll;
	lib_A506::func_80F("truck_explode_01","truck_explosion","truck_01_explode","truck_explode");
}

//Function Number: 4
func_5D34()
{
	level.var_78AE["seo_finale_phase2_rock_chunk01"] = #animtree;
	level.var_78B2["seo_finale_phase2_rock_chunk01"] = "rubble_rock_chunk_01";
	level.var_78A9["seo_finale_phase2_rock_chunk01"]["finale_pt03"] = %seo_finale_phase2_rock_chunk01;
	level.var_78AE["seo_finale_phase2_rock_chunk02"] = #animtree;
	level.var_78B2["seo_finale_phase2_rock_chunk02"] = "rubble_rock_chunk_01";
	level.var_78A9["seo_finale_phase2_rock_chunk02"]["finale_pt03"] = %seo_finale_phase2_rock_chunk02;
	level.var_78AE["seo_finale_phase2_sever_debris"] = #animtree;
	level.var_78B2["seo_finale_phase2_sever_debris"] = "mil_mwp_ending_metal_piece";
	level.var_78A9["seo_finale_phase2_sever_debris"]["finale_pt03"] = %seo_finale_phase2_sever_debris;
	level.var_78AE["seo_finale_phase2_sever_debris_02"] = #animtree;
	level.var_78B2["seo_finale_phase2_sever_debris_02"] = "fus_sever_debris_02";
	level.var_78A9["seo_finale_phase2_sever_debris_02"]["finale_pt03"] = %seo_finale_phase2_sever_debris_02;
	level.var_78AE["seo_finale_phase2_silo_burke_debris"] = #animtree;
	level.var_78B2["seo_finale_phase2_silo_burke_debris"] = "mil_mwp_ending_landing_gear";
	level.var_78A9["seo_finale_phase2_silo_burke_debris"]["finale_pt03"] = %seo_finale_phase2_silo_burke_debris;
	level.var_78AE["seo_finale_plantbomb_bomb"] = #animtree;
	level.var_78B2["seo_finale_plantbomb_bomb"] = "semx_explosive";
	level.var_78A9["seo_finale_plantbomb_bomb"]["finale_plantbomb"] = %seo_finale_plantbomb_bomb;
	level.var_78AE["seo_finale_part2_lamp01"] = #animtree;
	level.var_78B2["seo_finale_part2_lamp01"] = "ind_streetlight_single_off_rig";
	level.var_78A9["seo_finale_part2_lamp01"]["finale_pt02"] = %seo_finale_part2_lamp01;
	level.var_78AE["seo_finale_part2_lamp02"] = #animtree;
	level.var_78B2["seo_finale_part2_lamp02"] = "ind_streetlight_single_off_rig";
	level.var_78A9["seo_finale_part2_lamp02"]["finale_pt02"] = %seo_finale_part2_lamp02;
	level.var_78AE["seo_finale_part2_lamp03"] = #animtree;
	level.var_78B2["seo_finale_part2_lamp03"] = "ind_streetlight_single_off_rig";
	level.var_78A9["seo_finale_part2_lamp03"]["finale_pt02"] = %seo_finale_part2_lamp03;
	level.var_78AE["seo_finale_part2_lamp04"] = #animtree;
	level.var_78B2["seo_finale_part2_lamp04"] = "ind_streetlight_single_off_rig";
	level.var_78A9["seo_finale_part2_lamp04"]["finale_pt02"] = %seo_finale_part2_lamp04;
	level.var_78AE["seo_finale_part2_lamp05"] = #animtree;
	level.var_78B2["seo_finale_part2_lamp05"] = "ind_streetlight_single_off_rig";
	level.var_78A9["seo_finale_part2_lamp05"]["finale_pt02"] = %seo_finale_part2_lamp05;
	level.var_78AE["seo_finale_part2_lamp06"] = #animtree;
	level.var_78B2["seo_finale_part2_lamp06"] = "ind_streetlight_single_off_rig";
	level.var_78A9["seo_finale_part2_lamp06"]["finale_pt02"] = %seo_finale_part2_lamp06;
	level.var_78AE["seo_finale_part2_lamp07"] = #animtree;
	level.var_78B2["seo_finale_part2_lamp07"] = "ind_streetlight_single_off_rig";
	level.var_78A9["seo_finale_part2_lamp07"]["finale_pt02"] = %seo_finale_part2_lamp07;
	level.var_78AE["seo_finale_part2_lamp08"] = #animtree;
	level.var_78B2["seo_finale_part2_lamp08"] = "ind_streetlight_single_off_rig";
	level.var_78A9["seo_finale_part2_lamp08"]["finale_pt02"] = %seo_finale_part2_lamp08;
	level.var_78AE["zipline_anims"] = #animtree;
	level.var_78A9["zipline_anims"]["zipline_rope1"] = %zipline_rope1;
	level.var_78A9["zipline_anims"]["zipline_rope2"] = %zipline_rope2;
	level.var_78AE["grenade_training_crate"] = #animtree;
	level.var_78A9["grenade_training_crate"]["africa_militia_carry_crate_prop"] = %africa_militia_carry_crate_prop;
	level.var_78AE["door_anim"] = #animtree;
	level.var_78A9["door_anim"]["mulekick_kick"] = %ny_harbor_breech_mulekick_door_kick_open;
	level.var_78AE["cormack_door"] = #animtree;
	level.var_78A9["cormack_door"]["cormack_door_kick_start"] = %seo_door_kick_open_start_door;
	level.var_78A9["cormack_door"]["cormack_door_kick_idle"][0] = %seo_door_kick_open_idle_door;
	level.var_78A9["cormack_door"]["cormack_door_kick_end"] = %seo_door_kick_open_exit_door;
	level.var_78AE["exo_breach_door"] = #animtree;
	level.var_78A9["exo_breach_door"]["exo_punch_breach"] = %seo_hotel_breach_door;
	level.var_78AE["pod_seat_c"] = #animtree;
	level.var_78A9["pod_seat_c"]["pod_exit"] = %seo_pod_exit_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_exit"] = 0;
	level.var_78A9["pod_seat_c"]["pod_phase1a"] = %seo_pod_drop_phase1a_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_phase1a"] = 0;
	level.var_78A9["pod_seat_c"]["pod_phase1b"] = %seo_pod_drop_phase1b_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_phase1b"] = 0;
	level.var_78A9["pod_seat_c"]["pod_phase2b"] = %seo_pod_phase2b_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_phase2b"] = 0;
	level.var_78A9["pod_seat_c"]["pod_phase3"] = %seo_pod_phase3_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_phase3"] = 0;
	level.var_78A9["pod_seat_c"]["pod_phase3_add"] = %seo_pod_phase3_cormack_seat_add;
	level.var_78A9["pod_seat_c"]["pod_phase3_fail"] = %seo_pod_phase3_cormack_fail_seat;
	level.var_78B0["pod_seat_c"]["pod_phase3_fail"] = 0.333;
	level.var_78A9["pod_seat_c"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_phase4a_intro"] = 0;
	level.var_78A9["pod_seat_c"]["pod_phase4a"] = %seo_pod_phase4a_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_phase4a"] = 0;
	level.var_78A9["pod_seat_c"]["pod_phase4b"] = %seo_pod_phase4b_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_phase4b"] = 0;
	level.var_78A9["pod_seat_c"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_cormack_seat;
	level.var_78A9["pod_seat_c"]["pod_phase5"] = %seo_pod_phase5_cormack_seat;
	level.var_78A9["pod_seat_c"]["pod_wakeup"] = %seo_pod_crash_wake_up_cormack_seat;
	level.var_78B0["pod_seat_c"]["pod_wakeup"] = 0;
	level.var_78A9["pod_seat_c"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_cormack_idle_seat;
	level.var_8ADA["pod_seat_c"]["pod_wakeup_idle"] = 0;
	level.var_78AE["pod_seat_w"] = #animtree;
	level.var_78A9["pod_seat_w"]["pod_exit"] = %seo_pod_exit_will_seat;
	level.var_78B0["pod_seat_w"]["pod_exit"] = 0;
	level.var_78A9["pod_seat_w"]["pod_phase1a"] = %seo_pod_drop_phase1a_will_seat;
	level.var_78B0["pod_seat_w"]["pod_phase1a"] = 0;
	level.var_78A9["pod_seat_w"]["pod_phase1b"] = %seo_pod_drop_phase1b_will_seat;
	level.var_78B0["pod_seat_w"]["pod_phase1b"] = 0;
	level.var_78A9["pod_seat_w"]["pod_phase2b"] = %seo_pod_phase2b_will_seat;
	level.var_78B0["pod_seat_w"]["pod_phase2b"] = 0;
	level.var_78A9["pod_seat_w"]["pod_phase3"] = %seo_pod_phase3_will_seat;
	level.var_78B0["pod_seat_w"]["pod_phase3"] = 0;
	level.var_78A9["pod_seat_w"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_will_seat;
	level.var_78B0["pod_seat_w"]["pod_phase4a_intro"] = 0;
	level.var_78A9["pod_seat_w"]["pod_phase4a"] = %seo_pod_phase4a_will_seat;
	level.var_78B0["pod_seat_w"]["pod_phase4a"] = 0;
	level.var_78A9["pod_seat_w"]["pod_phase4b"] = %seo_pod_phase4b_will_seat;
	level.var_78B0["pod_seat_w"]["pod_phase4b"] = 0;
	level.var_78A9["pod_seat_w"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_will_seat;
	level.var_78A9["pod_seat_w"]["pod_phase5"] = %seo_pod_phase5_will_seat;
	level.var_78A9["pod_seat_w"]["pod_wakeup"] = %seo_pod_crash_wake_up_will_seat;
	level.var_78B0["pod_seat_w"]["pod_wakeup"] = 0;
	level.var_78A9["pod_seat_w"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_will_idle_seat;
	level.var_78B0["pod_seat_w"]["pod_wakeup_idle"] = 0;
	level.var_78AE["pod_seat_j"] = #animtree;
	level.var_78A9["pod_seat_j"]["pod_exit"] = %seo_pod_exit_jackson_seat;
	level.var_78B0["pod_seat_j"]["pod_exit"] = 0;
	level.var_78A9["pod_seat_j"]["pod_phase1a"] = %seo_pod_drop_phase1a_jackson_seat;
	level.var_78B0["pod_seat_j"]["pod_phase1a"] = 0;
	level.var_78A9["pod_seat_j"]["pod_phase1b"] = %seo_pod_drop_phase1b_jackson_seat;
	level.var_78B0["pod_seat_j"]["pod_phase1b"] = 0;
	level.var_78A9["pod_seat_j"]["pod_phase2b"] = %seo_pod_phase2b_jackson_seat;
	level.var_78B0["pod_seat_j"]["pod_phase2b"] = 0;
	level.var_78A9["pod_seat_j"]["pod_phase3"] = %seo_pod_phase3_jackson_seat;
	level.var_78B0["pod_seat_j"]["pod_phase4a_intro"] = 0;
	level.var_78A9["pod_seat_j"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_jackson_seat;
	level.var_78B0["pod_seat_j"]["pod_phase4a"] = 0;
	level.var_78A9["pod_seat_j"]["pod_phase4a"] = %seo_pod_phase4a_jackson_seat;
	level.var_78B0["pod_seat_j"]["pod_phase4b"] = 0;
	level.var_78A9["pod_seat_j"]["pod_phase4b"] = %seo_pod_phase4b_jackson_seat;
	level.var_78A9["pod_seat_j"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_jackson_seat;
	level.var_78A9["pod_seat_j"]["pod_phase5"] = %seo_pod_phase5_jackson_seat;
	level.var_78A9["pod_seat_j"]["pod_wakeup"] = %seo_pod_crash_wake_up_jackson_seat;
	level.var_78B0["pod_seat_j"]["pod_wakeup"] = 0;
	level.var_78AE["pod_seat_p"] = #animtree;
	level.var_78A9["pod_seat_p"]["pod_exit"] = %seo_pod_exit_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_exit"] = 0;
	level.var_78A9["pod_seat_p"]["pod_phase1a"] = %seo_pod_drop_phase1a_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_phase1a"] = 0;
	level.var_78A9["pod_seat_p"]["pod_phase1b"] = %seo_pod_drop_phase1b_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_phase1b"] = 0;
	level.var_78A9["pod_seat_p"]["pod_phase2b"] = %seo_pod_phase2b_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_phase2b"] = 0;
	level.var_78A9["pod_seat_p"]["pod_phase3"] = %seo_pod_phase3_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_phase3"] = 0;
	level.var_78A9["pod_seat_p"]["pod_phase3_fail"] = %seo_pod_phase3_vm_fail_seat;
	level.var_78B0["pod_seat_p"]["pod_phase3_fail"] = 0.333;
	level.var_78A9["pod_seat_p"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_phase4a"] = 0;
	level.var_78A9["pod_seat_p"]["pod_phase4a"] = %seo_pod_phase4a_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_phase4b"] = 0;
	level.var_78A9["pod_seat_p"]["pod_phase4b"] = %seo_pod_phase4b_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_phase5"] = %seo_pod_phase5_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_wakeup"] = %seo_pod_crash_wake_up_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_wakeup"] = 0;
	level.var_78A9["pod_seat_p"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_idle_vm_seat;
	level.var_78B0["pod_seat_p"]["pod_wakeup_idle"] = 0;
	level.var_78A9["pod_seat_p"]["pod_wakeup_right_1"] = %seo_pod_exit_unlock_right_1st_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_wakeup_right_1_idle"][0] = %seo_pod_exit_unlock_right_1st_idle_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_wakeup_left_2"] = %seo_pod_exit_unlock_left_2nd_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_wakeup_kick_idle"][0] = %seo_pod_exit_door_kick1_idle_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_wakeup_left_1"] = %seo_pod_exit_unlock_left_1st_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_wakeup_left_1_idle"][0] = %seo_pod_exit_unlock_left_1st_idle_vm_seat;
	level.var_78A9["pod_seat_p"]["pod_wakeup_right_2"] = %seo_pod_exit_unlock_right_2nd_vm_seat;
	level.var_78AE["pod_seat_1"] = #animtree;
	level.var_78A9["pod_seat_1"]["pod_exit"] = %seo_pod_exit_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_exit"] = 0;
	level.var_78A9["pod_seat_1"]["pod_phase1a"] = %seo_pod_drop_phase1a_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_phase1a"] = 0;
	level.var_78A9["pod_seat_1"]["pod_phase1b"] = %seo_pod_drop_phase1b_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_phase1b"] = 0;
	level.var_78A9["pod_seat_1"]["pod_phase2b"] = %seo_pod_phase2b_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_phase2b"] = 0;
	level.var_78A9["pod_seat_1"]["pod_phase3"] = %seo_pod_phase3_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_phase3"] = 0;
	level.var_78A9["pod_seat_1"]["pod_phase3_fail"] = %seo_pod_phase3_rack01_fail_seat;
	level.var_78B0["pod_seat_1"]["pod_phase3_fail"] = 0.333;
	level.var_78A9["pod_seat_1"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_phase4a_intro"] = 0;
	level.var_78A9["pod_seat_1"]["pod_phase4a"] = %seo_pod_phase4a_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_phase4a"] = 0;
	level.var_78A9["pod_seat_1"]["pod_phase4b"] = %seo_pod_phase4b_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_phase4b"] = 0;
	level.var_78A9["pod_seat_1"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_rack01_seat;
	level.var_78A9["pod_seat_1"]["pod_phase5"] = %seo_pod_phase5_rack01_seat;
	level.var_78A9["pod_seat_1"]["pod_wakeup"] = %seo_pod_crash_wake_up_rack01_seat;
	level.var_78B0["pod_seat_1"]["pod_wakeup"] = 0;
	level.var_78A9["pod_seat_1"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_rack01_idle_seat;
	level.var_78B0["pod_seat_1"]["pod_wakeup_idle"] = 0;
	level.var_78AE["pod_seat_2"] = #animtree;
	level.var_78A9["pod_seat_2"]["pod_exit"] = %seo_pod_exit_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_exit"] = 0;
	level.var_78A9["pod_seat_2"]["pod_phase1a"] = %seo_pod_drop_phase1a_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_phase1a"] = 0;
	level.var_78A9["pod_seat_2"]["pod_phase1b"] = %seo_pod_drop_phase1b_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_phase1b"] = 0;
	level.var_78A9["pod_seat_2"]["pod_phase2b"] = %seo_pod_phase2b_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_phase2b"] = 0;
	level.var_78A9["pod_seat_2"]["pod_phase3"] = %seo_pod_phase3_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_phase3"] = 0;
	level.var_78A9["pod_seat_2"]["pod_phase3_fail"] = %seo_pod_phase3_rack02_fail_seat;
	level.var_78B0["pod_seat_2"]["pod_phase3_fail"] = 0.333;
	level.var_78A9["pod_seat_2"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_phase4a_intro"] = 0;
	level.var_78A9["pod_seat_2"]["pod_phase4a"] = %seo_pod_phase4a_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_phase4a"] = 0;
	level.var_78A9["pod_seat_2"]["pod_phase4b"] = %seo_pod_phase4b_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_phase4b"] = 0;
	level.var_78A9["pod_seat_2"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_rack02_seat;
	level.var_78A9["pod_seat_2"]["pod_phase5"] = %seo_pod_phase5_rack02_seat;
	level.var_78A9["pod_seat_2"]["pod_wakeup"] = %seo_pod_crash_wake_up_rack02_seat;
	level.var_78B0["pod_seat_2"]["pod_wakeup"] = 0;
	level.var_78A9["pod_seat_2"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_rack02_idle_seat;
	level.var_78B0["pod_seat_2"]["pod_wakeup_idle"] = 0;
	level.var_78AE["pod_seat_3"] = #animtree;
	level.var_78A9["pod_seat_3"]["pod_exit"] = %seo_pod_exit_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_exit"] = 0;
	level.var_78A9["pod_seat_3"]["pod_phase1a"] = %seo_pod_drop_phase1a_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_phase1a"] = 0;
	level.var_78A9["pod_seat_3"]["pod_phase1b"] = %seo_pod_drop_phase1b_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_phase1b"] = 0;
	level.var_78A9["pod_seat_3"]["pod_phase2b"] = %seo_pod_phase2b_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_phase2b"] = 0;
	level.var_78A9["pod_seat_3"]["pod_phase3"] = %seo_pod_phase3_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_phase3"] = 0;
	level.var_78A9["pod_seat_3"]["pod_phase3_fail"] = %seo_pod_phase3_rack03_fail_seat;
	level.var_78B0["pod_seat_3"]["pod_phase3_fail"] = 0.333;
	level.var_78A9["pod_seat_3"]["pod_phase4a_intro"] = %seo_pod_phase4a_intro_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_phase4a_intro"] = 0;
	level.var_78A9["pod_seat_3"]["pod_phase4a"] = %seo_pod_phase4a_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_phase4a"] = 0;
	level.var_78A9["pod_seat_3"]["pod_phase4b"] = %seo_pod_phase4b_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_phase4b"] = 0;
	level.var_78A9["pod_seat_3"]["pod_phase4b_crash"] = %seo_pod_phase4b_crash_rack03_seat;
	level.var_78A9["pod_seat_3"]["pod_phase5"] = %seo_pod_phase5_rack03_seat;
	level.var_78A9["pod_seat_3"]["pod_wakeup"] = %seo_pod_crash_wake_up_rack03_seat;
	level.var_78B0["pod_seat_3"]["pod_wakeup"] = 0;
	level.var_78A9["pod_seat_3"]["pod_wakeup_idle"][0] = %seo_pod_crash_wake_up_rack03_idle_seat;
	level.var_78B0["pod_seat_3"]["pod_wakeup_idle"] = 0;
	level.var_78AE["pod_missile_blimp"] = #animtree;
	level.var_78B2["pod_missile_blimp"] = "projectile_javelin_missile";
	level.var_78A9["pod_missile_blimp"]["pod_phase1b"] = %seo_pod_drop_phase1b_missile;
	lib_A506::func_807("pod_missile_blimp","vfx_ missile trail",::lib_A5CE::func_4EF0,"pod_phase1b");
	lib_A506::func_807("pod_missile_blimp","vfx_trail delete",::lib_A5CE::func_4EF1,"pod_phase1b");
	level.var_78AE["pod_missile_final"] = #animtree;
	level.var_78A9["pod_missile_final"]["pod_phase2b"] = %seo_pod_phase2b_final_missle;
	lib_A506::func_807("pod_missile_final","vfx_intro_missile",::lib_A5CE::func_4F44,"pod_phase2b");
	lib_A506::func_807("pod_missile_final","vfx_intro_missile_delete",::lib_A5CE::func_4F45,"pod_phase2b");
	level.var_78AE["pod_missile_1"] = #animtree;
	level.var_78A9["pod_missile_1"]["pod_phase2b"] = %seo_pod_phase2b_missle_group_01;
	lib_A506::func_807("pod_missile_1","vfx_intro_missile",::lib_A5CE::func_4F44,"pod_phase2b");
	lib_A506::func_807("pod_missile_1","vfx_intro_missile_delete",::lib_A5CE::func_4F45,"pod_phase2b");
	level.var_78AE["pod_missile_2"] = #animtree;
	level.var_78A9["pod_missile_2"]["pod_phase2b"] = %seo_pod_phase2b_missle_group_02;
	lib_A506::func_807("pod_missile_2","vfx_intro_missile",::lib_A5CE::func_4F44,"pod_phase2b");
	lib_A506::func_807("pod_missile_2","vfx_intro_missile_delete",::lib_A5CE::func_4F45,"pod_phase2b");
	level.var_78AE["pod_missile_3"] = #animtree;
	level.var_78A9["pod_missile_3"]["pod_phase2b"] = %seo_pod_phase2b_missle_group_03;
	lib_A506::func_807("pod_missile_3","vfx_intro_missile",::lib_A5CE::func_4F44,"pod_phase2b");
	lib_A506::func_807("pod_missile_3","vfx_intro_missile_delete",::lib_A5CE::func_4F45,"pod_phase2b");
	level.var_78AE["pod_missile_4"] = #animtree;
	level.var_78A9["pod_missile_4"]["pod_phase2b"] = %seo_pod_phase2b_missle_group_04;
	level.var_78AE["pod_missile_5"] = #animtree;
	level.var_78A9["pod_missile_5"]["pod_phase2b"] = %seo_pod_phase2b_missle_group_05;
	level.var_78AE["pod_missile_6"] = #animtree;
	level.var_78A9["pod_missile_6"]["pod_phase2b"] = %seo_pod_phase2b_missle_group_06;
	level.var_78AE["subway_gate"] = #animtree;
	level.var_78B2["subway_gate"] = "genericprop";
	level.var_78A9["subway_gate"]["seo_meet_atlas"] = %seo_meet_atlas_gate;
	level.var_78AE["roof_chunks"] = #animtree;
	level.var_78B2["roof_chunks"] = "seo_roof_chunk";
	level.var_78A9["roof_chunks"]["seo_meet_atlas"] = %seo_meet_atlas_roof_chunks;
	lib_A506::func_807("roof_chunks","roof_explosion",::maps\seoul_code_shopping_district::func_8F9A,"seo_meet_atlas");
	lib_A506::func_807("roof_chunks","roof_explosion",::lib_A5CE::func_75A4,"seo_meet_atlas");
	level.var_78AE["player_gun"] = #animtree;
	level.var_78A9["player_gun"]["seo_meet_atlas"] = %seo_meet_atlas_gun;
	level.var_78AE["binocs"] = #animtree;
	level.var_78B2["binocs"] = "soflam_laser_designator_scripted";
	level.var_78A9["binocs"]["seo_canal_debrief_scanning_intro_vm"] = %seo_canal_debrief_scanning_intro_binoculars;
	level.var_78A9["binocs"]["seo_canal_debrief_scanning_outro_vm"] = %seo_canal_debrief_scanning_outro_binoculars;
}

//Function Number: 5
func_3648(param_00)
{
	level notify("fire_fake_rocket_now");
}